### ISSUE TITLE
Cookie file cannot be read and written: (null)

### ISSUE THREAD

**Issue by nikhil003** [Unidata/netcdf4-python#1039]
We are trying to read a list of files hosted on a thredds using `nc.MFDataset` and are getting the following error

> 
> Cookie file cannot be read and written: (null)

>   File "C:\geoweb\geoweb-core\python\vcp19\aplc_catalog.py", line 657, in __init__
>     self._handle = nc.MFDataset(self._file_path)
>   File "netCDF4\_netCDF4.pyx", line 6275, in netCDF4._netCDF4.MFDataset.__init__
>   File "netCDF4\_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
>   File "netCDF4\_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
> OSError: [Errno -37] NetCDF: Write to read only: b'http://cloudstar-cl.nexus.csiro.au/thredds/dodsC/gldas/2020/03/GLDAS_CLSM025_DA1_D.A20200327.022.nc'

after some testing, we have found that the error is limited to windows platform. It seems to be working correctly on both linux and mac machines. When digging through the source code of netcdf-c library, we found that the error is triggered in the [oc2](https://github.com/Unidata/netcdf-c/blob/cb6e990cd148992e01e858f5300d91d11f06f642/oc2/ocinternal.c#L581) module in the netcdf library. We would really appreciate some help in sorting this issue out.

**Comment by jswhit** [comment]
MFDataset doesn't explicitly support accessing thredds datasets - it might work, I've just never tried it.   Does this error happen on windows even with a single URL opened with `netCDF4.Dataset`?  If so, I suggest opening a netcdf-c ticket since this is a problem on the c side.

**Comment by Yukon-climate** [comment]
@nikhil003 Did you ever figured out what was wrong?

I am running into the same sort of issues on a linux docker container: 

```
import netCDF4
ds = netCDF4.Dataset('http://thredds.socib.es/thredds/dodsC/hf_radar/hf_radar_ibiza-scb_codarssproc001/L1/2016/dep0001_hf-radar-ibiza_scb-codarssproc001_L1_2016-02.nc')
```

Which returns : 

```
Cookie file cannot be read and written: /root/.esg/.dods_cookies
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-34-2f0f671b7034> in <module>
----> 1 ds = netCDF4.Dataset('http://thredds.socib.es/thredds/dodsC/hf_radar/hf_radar_ibiza-scb_codarssproc001/L1/2016/dep0001_hf-radar-ibiza_scb-codarssproc001_L1_2016-02.nc')

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -37] NetCDF: Write to read only: b'http://thredds.socib.es/thredds/dodsC/hf_radar/hf_radar_ibiza-scb_codarssproc001/L1/2016/dep0001_hf-radar-ibiza_scb-codarssproc001_L1_2016-02.nc'
```

NetCDF4 version : '1.5.4'

**Comment by KP92-KP** [comment]
import netCDF4 as nc4
import numpy as np

URL = 'https://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/1980/01/MERRA2_100.tavg1_2d_slv_Nx.19800101.nc4'
f = nc4.Dataset(URL, 'r')
t2m = f['t2m']

**Comment by KP92-KP** [comment]
`import netCDF4 as nc4
import numpy as np

URL = 'https://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/1980/01/MERRA2_100.tavg1_2d_slv_Nx.19800101.nc4'
f = nc4.Dataset(URL, 'r')
t2m = f['t2m']`

**Comment by jswhit** [comment]
All of these examples work for me on macos x and linux. It must be a platform or version specific issue with the netcdf-c library.  Since the python interface does nothing but forward the URL to netcdf-c, it's not something that can be fixed here.  I suggest creating an issue [here](https://github.com/Unidata/netcdf-c/issues).

**Comment by KP92-KP** [comment]
Which version of netcdf lib does netCDF4 use?

**Comment by liellnima** [comment]
We had the same issue and it turned out that the real problem is the cookie error message! It's a broken cookie that was created e.g. during a logon process and wasn't properly deleted (either at all or the logoff messed sth up). In our case, the cookie itself couldn't be found at the specified path, but we found it in `.dodsrc`. 

Deleted the `.dodsrc` file and everything run smoothly. 

(This  solution applies only to those cases where the cookie error message popped up, of course)
