### ISSUE TITLE
Release >=1.5.3 breaking with I/O failure on macOS

### ISSUE THREAD

**Issue by rollingwindow** [Unidata/netcdf4-python#1052]
Hi,

When trying to load a dataset with netCDF4 I get the following:

```
curl error details: 
Traceback (most recent call last):
  File "scratch/opendap.py", line 9, in <module>
    ds = Dataset(dataset.opendap_url)
  File "netCDF4/_netCDF4.pyx", line 2358, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1926, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -68] NetCDF: I/O failure: b'http://nomads.ncep.noaa.gov:80/dods/gfs_0p50/gfs20201212/gfs_0p50_06z'    
```  

Reverting to 1.5.2 solves the problem.

--
Python Version: 3.8.2
System Version: macOS 10.15.6 (19G2021)
Kernel Version: Darwin 19.6.0

**Comment by jswhit** [comment]
Nothing has changed in the python interface that would affect this, so I suspect is a C-lib issue (curl or netcdf-c).  How are you installing netcdf4-python? What versions of the C libs are linked for 1.5.2 and 1.5.3?  (you can check with this script

```
import netCDF4
print('netcdf4-python version: %s\n'%netCDF4.__version__)
print('HDF5 lib version:       %s\n'%netCDF4.__hdf5libversion__)
print('netcdf lib version:     %s\n'%netCDF4.__netcdf4libversion__)
```

**Comment by jswhit** [comment]
on macOS, 'otool -L' on netCDF4.so will tell you what libnetcdf is being linked.  Once you know that, you can run 'otool -L' on that dylib and see which hdf5 and curl libs are being used.  There must be some difference in the libs linked between 1.5.2 and 1.5.3.

**Comment by demarg** [comment]
after pip installing netcdf4==1.5.2:
```
>>> import netCDF4
>>> print('netcdf4-python version: %s'%netCDF4.__version__)
netcdf4-python version: 1.5.2
>>> print('HDF5 lib version:       %s'%netCDF4.__hdf5libversion__)
HDF5 lib version:       1.12.0
>>> print('netcdf lib version:     %s'%netCDF4.__netcdf4libversion__)
netcdf lib version:     4.7.4
```

after pip installing netcdf4==1.5.3:

```
>>> import netCDF4
>>> print('netcdf4-python version: %s'%netCDF4.__version__)
netcdf4-python version: 1.5.3
>>> print('HDF5 lib version:       %s'%netCDF4.__hdf5libversion__)
HDF5 lib version:       1.10.4
>>> print('netcdf lib version:     %s'%netCDF4.__netcdf4libversion__)
netcdf lib version:     4.6.3
```

after pip installing netcdf4==1.5.5:
```
>>> import netCDF4
>>> print('netcdf4-python version: %s'%netCDF4.__version__)
netcdf4-python version: 1.5.5
>>> print('HDF5 lib version:       %s'%netCDF4.__hdf5libversion__)
HDF5 lib version:       1.10.5
>>> print('netcdf lib version:     %s'%netCDF4.__netcdf4libversion__)
netcdf lib version:     4.6.3
```

So it seems to revert HDF5 & netcdf...

**Comment by jswhit** [comment]
so it's installing the binary wheels from pypi? I will have to check and see why they were built against an older netcdf-c/hdf5 libs.

**Comment by jswhit** [comment]
I've updated the wheel building repo to use netcdf-c 4.7.4 so the next release on pypi will use the new libs.

I can make a 1.5.5.1 release next week which just updates the binary wheels if need be.

**Comment by rollingwindow** [comment]
Thanks a lot for looking into this. Feel free to release when it suits you, there's no hurry.

**Comment by jswhit** [comment]
New release up on pypi

**Comment by d70-t** [comment]
I am having an issue which seems to be very similar to this one. I am running MacOS 11.1

When I install python netCDF4 1.5.3 running `tst_dap.py` seems to be fine:
```
% python3 -m pip install netcdf4==1.5.3
Requirement already satisfied: netcdf4==1.5.3 in /usr/local/lib/python3.9/site-packages (1.5.3)
Requirement already satisfied: numpy>=1.7 in /usr/local/lib/python3.9/site-packages (from netcdf4==1.5.3) (1.20.1)
Requirement already satisfied: cftime in /usr/local/lib/python3.9/site-packages (from netcdf4==1.5.3) (1.3.1)
% python3 check_versions.py            
netcdf4-python version: 1.5.3
HDF5 lib version:       1.12.0
netcdf lib version:     4.7.4
% python3 -m pytest tst_dap.py         
============================================================================= test session starts =============================================================================
platform darwin -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/tobi/Documents/code/netcdf4_bug
collected 1 item                                                                                                                                                              

tst_dap.py .                                                                                                                                                            [100%]

============================================================================== warnings summary ===============================================================================
tst_dap.py::DapTestCase::runTest
  /Users/tobi/Documents/code/netcdf4_bug/tst_dap.py:28: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    data = var[:]

tst_dap.py::DapTestCase::runTest
  /Users/tobi/Documents/code/netcdf4_bug/tst_dap.py:34: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
    assert(ncfile['sst'].long_name=='Sea Surface Temperature')

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================================================== 1 passed, 2 warnings in 3.58s ========================================================================
% 
```

However, as soon as I upgrade to either `1.5.4` or `1.5.5.1`, the following error occurs:
```
% python3 -m pip install netcdf4==1.5.5.1
Collecting netcdf4==1.5.5.1
  Using cached netCDF4-1.5.5.1-cp39-cp39-macosx_10_9_x86_64.whl (4.1 MB)
Requirement already satisfied: cftime in /usr/local/lib/python3.9/site-packages (from netcdf4==1.5.5.1) (1.3.1)
Requirement already satisfied: numpy>=1.9 in /usr/local/lib/python3.9/site-packages (from netcdf4==1.5.5.1) (1.20.1)
Installing collected packages: netcdf4
  Attempting uninstall: netcdf4
    Found existing installation: netCDF4 1.5.3
    Uninstalling netCDF4-1.5.3:
      Successfully uninstalled netCDF4-1.5.3
Successfully installed netcdf4-1.5.5.1
% python3 check_versions.py              
netcdf4-python version: 1.5.5.1
HDF5 lib version:       1.12.0
netcdf lib version:     4.7.4
% python3 -m pytest tst_dap.py           
============================================================================= test session starts =============================================================================
platform darwin -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/tobi/Documents/code/netcdf4_bug
collected 1 item                                                                                                                                                              

tst_dap.py F                                                                                                                                                            [100%]

================================================================================== FAILURES ===================================================================================
_____________________________________________________________________________ DapTestCase.runTest _____________________________________________________________________________

self = <tst_dap.DapTestCase testMethod=runTest>

    def runTest(self):
        """testing access of data over http using opendap"""
>       ncfile = netCDF4.Dataset(URL)

tst_dap.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
netCDF4/_netCDF4.pyx:2357: in netCDF4._netCDF4.Dataset.__init__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   OSError: [Errno -68] NetCDF: I/O failure: b'http://remotetest.unidata.ucar.edu/thredds/dodsC/testdods/testData.nc'

netCDF4/_netCDF4.pyx:1925: OSError
---------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------
curl error details: 
=========================================================================== short test summary info ===========================================================================
FAILED tst_dap.py::DapTestCase::runTest - OSError: [Errno -68] NetCDF: I/O failure: b'http://remotetest.unidata.ucar.edu/thredds/dodsC/testdods/testData.nc'
============================================================================== 1 failed in 0.66s ==============================================================================
% 
```

Thus while the versions of netcdf-c and HDF5 stay the same, the opendap error changes.

**Comment by jswhit** [comment]
That test is working for me now, maybe the server was just down temporarily?  You can disable the opendap tests by setting the env var NO_NET.

**Comment by d70-t** [comment]
That is mysterious. I think it's not about the server. I've tried to access two different opendap servers as well with the same result. And I tried all Versions from 1.5.0 through 1.5.5.1 and exactly at the change between 1.5.3 and 1.5.4 this error appears. And I can cycle back and forth between the versions, but the error only appears at netcdf4-python versions > 1.5.3 (interestingly not >**=** 1.5.3 though).

**Comment by jswhit** [comment]
That may have been when I switched to using the OSX supplied curl lib in the binary wheels, instead of building and bundling curl in the binary wheel.

**Comment by d70-t** [comment]
Is it possible, that this somehow interferes with things installed by homebrew?

**Comment by jswhit** [comment]
IDK

**Comment by jswhit** [comment]
actually, the switch to using built-in curl happened in 1.5.5 so NVM.  Nothing changed in the libs used in the 1.5.4 release AFAICT.

**Comment by jswhit** [comment]
you are installing with pip, correct?

**Comment by d70-t** [comment]
> you are installing with pip, correct?

Yes, that's correct.

**Comment by jswhit** [comment]
I'm stumped then.  Can you access other datasets via opendap?

**Comment by d70-t** [comment]
No, that's the problem. I can't access any dataset via opendap anymore with the newer versions 🤷

**Comment by d70-t** [comment]
I now tried to run the thin with `export DYLD_PRINT_LIBRARIES=1`, which shows which libraries actually are loaded. Probably that helps for the investigation?

This is for curl
```
dyld_debug_1.5.0.txt
dyld: loaded: <C9541242-9ED5-3F9B-A2B2-415503447A1F> /usr/lib/libcurl.4.dylib
dyld_debug_1.5.1.txt
dyld: loaded: <C9541242-9ED5-3F9B-A2B2-415503447A1F> /usr/lib/libcurl.4.dylib
dyld_debug_1.5.2.txt
dyld: loaded: <C9541242-9ED5-3F9B-A2B2-415503447A1F> /usr/lib/libcurl.4.dylib
dyld_debug_1.5.3.txt
dyld: loaded: <C9541242-9ED5-3F9B-A2B2-415503447A1F> /usr/lib/libcurl.4.dylib
dyld_debug_1.5.4.txt
dyld: loaded: <D1789284-C91D-3179-BAC2-455849BD8C21> /usr/local/lib/python3.9/site-packages/netCDF4/.dylibs/libcurl.4.dylib
curl error details: 
dyld_debug_1.5.5.1.txt
dyld: loaded: <D1789284-C91D-3179-BAC2-455849BD8C21> /usr/local/lib/python3.9/site-packages/netCDF4/.dylibs/libcurl.4.dylib
curl error details: 
dyld_debug_1.5.5.txt
dyld: loaded: <D1789284-C91D-3179-BAC2-455849BD8C21> /usr/local/lib/python3.9/site-packages/netCDF4/.dylibs/libcurl.4.dylib
```

And that for netcdf
```
dyld_debug_1.5.0.txt
dyld: loaded: <933A80FE-9296-3BC8-B75E-72219F5B211A> /usr/local/opt/netcdf/lib/libnetcdf.18.dylib
dyld_debug_1.5.1.txt
dyld: loaded: <933A80FE-9296-3BC8-B75E-72219F5B211A> /usr/local/opt/netcdf/lib/libnetcdf.18.dylib
dyld_debug_1.5.2.txt
dyld: loaded: <933A80FE-9296-3BC8-B75E-72219F5B211A> /usr/local/opt/netcdf/lib/libnetcdf.18.dylib
dyld_debug_1.5.3.txt
dyld: loaded: <933A80FE-9296-3BC8-B75E-72219F5B211A> /usr/local/opt/netcdf/lib/libnetcdf.18.dylib
dyld_debug_1.5.4.txt
dyld: loaded: <C20CA4AD-6F3D-344C-8CAE-1BFB9B832FFE> /usr/local/lib/python3.9/site-packages/netCDF4/.dylibs/libnetcdf.15.dylib
  File "/Users/tobi/Documents/code/netcdf4_bug/simpletest.py", line 4, in <module>
dyld_debug_1.5.5.1.txt
dyld: loaded: <16687448-BBDB-39CE-9C4E-CD0D2B6E34E0> /usr/local/lib/python3.9/site-packages/netCDF4/.dylibs/libnetcdf.18.dylib
  File "/Users/tobi/Documents/code/netcdf4_bug/simpletest.py", line 4, in <module>
dyld_debug_1.5.5.txt
dyld: loaded: <F500CD64-FA6E-364F-A141-60B624024AF2> /usr/local/lib/python3.9/site-packages/netCDF4/.dylibs/libnetcdf.15.dylib
  File "/Users/tobi/Documents/code/netcdf4_bug/simpletest.py", line 4, in <module>
```

**Comment by d70-t** [comment]
To me, this looks like a change between system libraries and bundled libraries. But I almost don't know anything about how bundling of libraries and wheels work in python.

**Comment by jswhit** [comment]
I would agree.  I don't know how to fix it though, besides switching to the conda package or building it yourself from source.

**Comment by jswhit** [comment]
Just tried installing the 1.5.5.1 wheel for python3.8 on my mac, and I now get a segfault trying to run the opendap test.

**Comment by jswhit** [comment]
Building the wheels with a newer version of curl seems to fix this.  I will make a new release this week.  Pre-release wheels at https://github.com/MacPython/netcdf4-python-wheels/releases/tag/v1.5.6rel if you want to try one out.

**Comment by d70-t** [comment]
Thanks @jswhit I installed `netCDF4-1.5.6-cp39-cp39-macosx_10_9_x86_64.whl` and the test passes on my machine 🎉

**Comment by jswhit** [comment]
1.5.6 is released
