### ISSUE TITLE
Unlimited dimensions can't grow when parallel=True

### ISSUE THREAD

**Issue by Mo-Dabao** [Unidata/netcdf4-python#1072]
My code:
```python
# test.py
from datetime import datetime

import numpy as np
from netCDF4 import Dataset as ncds
from mpi4py.futures import MPIPoolExecutor
from mpi4py import MPI

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

def func(p):
    for n in range(4):
        print(f'rank{rank} is touching {n}.nc at {p}')
        nc_path = f'{n}.nc'
        try:
            nc_file = ncds(nc_path, 'a', parallel=True)
            t = nc_file['t']
            t.set_collective(True)
            t[p] = p
            x = nc_file['x']
            x.set_collective(True)
            x[p] = n * p
            # nc_file.sync()
            nc_file.close()
            # del nc_file
            print(f'rank{rank} is leaving {n}.nc at {p}')
        except Exception as e:
            print(e)

if __name__ == '__main__':
    for n in range(4):
        nc_path = f'{n}.nc'
        nc_file = ncds(nc_path, 'w')
        nc_file.createDimension('t', None)
        nc_file.createVariable('t', 'i2', ('t',))
        nc_file.createVariable('x', 'i4', ('t',))
        nc_file.close()
    start = datetime.now()
    with MPIPoolExecutor(max_workers=2) as pool:
        pool.map(func, range(5))
    stop = datetime.now()
    print(stop - start)
```
Wrong like:
```
(base) modabao@Enterprise:~$ /home/modabao/miniconda3/bin/python /home/modabao/test.py
rank1 is touching 0.nc at 1
rank0 is touching 0.nc at 0
python: H5Fio.c:195: H5F_shared_block_write: Assertion `((addr)!=((haddr_t)(long)(-1)))' failed.
python: H5Fio.c:195: H5F_shared_block_write: Assertion `((addr)!=((haddr_t)(long)(-1)))' failed.
[Enterprise:26556] *** Process received signal ***
[Enterprise:26556] Signal: Aborted (6)
[Enterprise:26556] Signal code:  (-6)
[Enterprise:26557] *** Process received signal ***
[Enterprise:26557] Signal: Aborted (6)
[Enterprise:26557] Signal code:  (-6)
[Enterprise:26556] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f731afa53c0]
[Enterprise:26556] [ 1] [Enterprise:26557] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7fe533d833c0]
[Enterprise:26557] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f731ade418b]
[Enterprise:26556] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f731adc3859]
[Enterprise:26556] [ 3] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7fe533bc218b]
[Enterprise:26557] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7fe533ba1859]
[Enterprise:26557] [ 3] /lib/x86_64-linux-gnu/libc.so.6(+0x25729)[0x7f731adc3729]
[Enterprise:26556] [ 4] /lib/x86_64-linux-gnu/libc.so.6(+0x36f36)[0x7f731add4f36]
[Enterprise:26556] [ 5] /lib/x86_64-linux-gnu/libc.so.6(+0x25729)[0x7fe533ba1729]
[Enterprise:26557] [ 4] /lib/x86_64-linux-gnu/libc.so.6(+0x36f36)[0x7fe533bb2f36]
[Enterprise:26557] [ 5] /usr/local/lib/libhdf5.so.200(H5F_shared_block_write+0x1e2)[0x7f73104a1bd3]
[Enterprise:26556] [ 6] /usr/local/lib/libhdf5.so.200(H5F_shared_block_write+0x1e2)[0x7fe5282c2bd3]
[Enterprise:26557] [ 6] /usr/local/lib/libhdf5.so.200(H5D__mpio_select_write+0x7f)[0x7f73107dfb4b]
[Enterprise:26556] [ 7] /usr/local/lib/libhdf5.so.200(H5D__mpio_select_write+0x7f)[0x7fe528600b4b]
[Enterprise:26557] [ 7] /usr/local/lib/libhdf5.so.200(+0x4d447b)[0x7fe5285f647b]
[Enterprise:26557] [ 8] /usr/local/lib/libhdf5.so.200(+0x4d447b)[0x7f73107d547b]
[Enterprise:26556] [ 8] /usr/local/lib/libhdf5.so.200(+0x4d4621)[0x7fe5285f6621]
[Enterprise:26557] [ 9] /usr/local/lib/libhdf5.so.200(+0x4d4621)[0x7f73107d5621]
[Enterprise:26556] [ 9] /usr/local/lib/libhdf5.so.200(+0x4da605)[0x7fe5285fc605]
[Enterprise:26557] [10] /usr/local/lib/libhdf5.so.200(+0x4da605)[0x7f73107db605]
[Enterprise:26556] [10] /usr/local/lib/libhdf5.so.200(+0x4de45f)[0x7fe52860045f]
[Enterprise:26557] [11] /usr/local/lib/libhdf5.so.200(+0x4de45f)[0x7f73107df45f]
[Enterprise:26556] [11] /usr/local/lib/libhdf5.so.200(H5D__chunk_collective_write+0x70)[0x7f73107dfffb]
[Enterprise:26556] [12] /usr/local/lib/libhdf5.so.200(H5D__chunk_collective_write+0x70)[0x7fe528600ffb]
[Enterprise:26557] [12] /usr/local/lib/libhdf5.so.200(H5D__write+0x543)[0x7f7310445f71]
[Enterprise:26556] [13] /usr/local/lib/libhdf5.so.200(H5D__write+0x543)[0x7fe528266f71]
[Enterprise:26557] [13] /usr/local/lib/libhdf5.so.200(H5VL__native_dataset_write+0xbf)[0x7f73107a1f72]
[Enterprise:26556] [14] /usr/local/lib/libhdf5.so.200(H5VL__native_dataset_write+0xbf)[0x7fe5285c2f72]
[Enterprise:26557] [14] /usr/local/lib/libhdf5.so.200(+0x47a2ae)[0x7f731077b2ae]
[Enterprise:26556] [15] /usr/local/lib/libhdf5.so.200(+0x47a2ae)[0x7fe52859c2ae]
[Enterprise:26557] [15] /usr/local/lib/libhdf5.so.200(H5VL_dataset_write+0xb8)[0x7f731078641c]
[Enterprise:26556] [16] /usr/local/lib/libhdf5.so.200(H5VL_dataset_write+0xb8)[0x7fe5285a741c]
[Enterprise:26557] [16] /usr/local/lib/libhdf5.so.200(H5Dwrite+0x161)[0x7f7310444389]
[Enterprise:26556] [17] /usr/local/lib/libnetcdf.so.18(NC4_put_vars+0xd21)[0x7f73109a58d9]
[Enterprise:26556] [18] /usr/local/lib/libhdf5.so.200(H5Dwrite+0x161)[0x7fe528265389]
[Enterprise:26557] [17] /usr/local/lib/libnetcdf.so.18(NC4_put_vars+0xd21)[0x7fe5287c68d9]
[Enterprise:26557] [18] /usr/local/lib/libnetcdf.so.18(NC4_put_vara+0x4c)[0x7fe5287c59fd]
[Enterprise:26557] [19] /usr/local/lib/libnetcdf.so.18(+0x2c300)[0x7fe528760300]
[Enterprise:26557] [20] /usr/local/lib/libnetcdf.so.18(NC4_put_vara+0x4c)[0x7f73109a49fd]
[Enterprise:26556] [19] /usr/local/lib/libnetcdf.so.18(+0x2c300)[0x7f731093f300]
[Enterprise:26556] [20] /usr/local/lib/libnetcdf.so.18(nc_put_vara+0x90)[0x7fe528761a37]
[Enterprise:26557] [21] /home/modabao/miniconda3/lib/python3.8/site-packages/netCDF4-1.5.5-py3.8-linux-x86_64.egg/netCDF4/_netCDF4.cpython-38-x86_64-linux-gnu.so(+0xe7111)[0x7fe52893c111]
[Enterprise:26557] [22] /usr/local/lib/libnetcdf.so.18(nc_put_vara+0x90)[0x7f7310940a37]
[Enterprise:26556] [21] /home/modabao/miniconda3/lib/python3.8/site-packages/netCDF4-1.5.5-py3.8-linux-x86_64.egg/netCDF4/_netCDF4.cpython-38-x86_64-linux-gnu.so(+0xe7111)[0x7f7310b1b111]
[Enterprise:26556] [22] /home/modabao/miniconda3/bin/python(PyCFunction_Call+0x56)[0x560ff537ff76]
[Enterprise:26557] [23] /home/modabao/miniconda3/bin/python(PyCFunction_Call+0x56)[0x556bbdd68f76]
[Enterprise:26556] [23] /home/modabao/miniconda3/lib/python3.8/site-packages/netCDF4-1.5.5-py3.8-linux-x86_64.egg/netCDF4/_netCDF4.cpython-38-x86_64-linux-gnu.so(+0x22eb6)[0x7f7310a56eb6]
[Enterprise:26556] [24] /home/modabao/miniconda3/lib/python3.8/site-packages/netCDF4-1.5.5-py3.8-linux-x86_64.egg/netCDF4/_netCDF4.cpython-38-x86_64-linux-gnu.so(+0xc4116)[0x7f7310af8116]
[Enterprise:26556] [25] /home/modabao/miniconda3/bin/python(_PyEval_EvalFrameDefault+0x104a)[0x556bbddaaa0a]
[Enterprise:26556] [26] /home/modabao/miniconda3/lib/python3.8/site-packages/netCDF4-1.5.5-py3.8-linux-x86_64.egg/netCDF4/_netCDF4.cpython-38-x86_64-linux-gnu.so(+0x22eb6)[0x7fe528877eb6]
[Enterprise:26557] [24] /home/modabao/miniconda3/lib/python3.8/site-packages/netCDF4-1.5.5-py3.8-linux-x86_64.egg/netCDF4/_netCDF4.cpython-38-x86_64-linux-gnu.so(+0xc4116)[0x7fe528919116]
[Enterprise:26557] [25] /home/modabao/miniconda3/bin/python(_PyEval_EvalFrameDefault+0x104a)[0x560ff53c1a0a]
[Enterprise:26557] [26] /home/modabao/miniconda3/bin/python(_PyFunction_Vectorcall+0x10b)[0x560ff538b86b]
[Enterprise:26557] [27] /home/modabao/miniconda3/bin/python(_PyFunction_Vectorcall+0x10b)[0x556bbdd7486b]
[Enterprise:26556] [27] /home/modabao/miniconda3/bin/python(PyVectorcall_Call+0x71)[0x556bbdd26041]
[Enterprise:26556] [28] /home/modabao/miniconda3/bin/python(PyVectorcall_Call+0x71)[0x560ff533d041]
[Enterprise:26557] [28] /home/modabao/miniconda3/bin/python(_PyEval_EvalFrameDefault+0x1fdb)[0x556bbddab99b]
[Enterprise:26556] [29] /home/modabao/miniconda3/bin/python(_PyEval_EvalFrameDefault+0x1fdb)[0x560ff53c299b]
[Enterprise:26557] [29] /home/modabao/miniconda3/bin/python(_PyEval_EvalCodeWithName+0x2d2)[0x560ff538aa92]
/home/modabao/miniconda3/bin/python(_PyEval_EvalCodeWithName+0x2d2)[0x556bbdd73a92]
[Enterprise:26556] *** End of error message ***
[Enterprise:26557] *** End of error message ***
--------------------------------------------------------------------------
Child job 2 terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
^CTraceback (most recent call last):
  File "/home/modabao/test.py", line 40, in <module>
    pool.map(func, range(5))
  File "/home/modabao/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 636, in __exit__
    self.shutdown(wait=True)
  File "/home/modabao/miniconda3/lib/python3.8/site-packages/mpi4py/futures/pool.py", line 179, in shutdown
    self._pool.join()
  File "/home/modabao/miniconda3/lib/python3.8/site-packages/mpi4py/futures/_lib.py", line 136, in join
    self.thread.join()
  File "/home/modabao/miniconda3/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/modabao/miniconda3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/modabao/miniconda3/lib/python3.8/site-packages/mpi4py/futures/_lib.py", line 102, in join_threads
    thread.join()
  File "/home/modabao/miniconda3/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/modabao/miniconda3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

--------------------------------------------------------------------------
(null) noticed that process rank 0 with PID 0 on node Enterprise exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```
But if chane
```python
        nc_file.createDimension('t', None)
```
to
```python
        nc_file.createDimension('t', 5)
```
It stops complaining, but stucks (deadlock?):
```
(base) modabao@Enterprise:~$ /home/modabao/miniconda3/bin/python /home/modabao/test.py
rank0 is touching 0.nc at 0
rank1 is touching 0.nc at 1
rank0 is leaving 0.nc at 0
rank0 is touching 1.nc at 0
rank1 is leaving 0.nc at 1
rank1 is touching 1.nc at 1
rank0 is leaving 1.nc at 0
rank0 is touching 2.nc at 0
rank1 is leaving 1.nc at 1
rank1 is touching 2.nc at 1
rank0 is leaving 2.nc at 0
rank0 is touching 3.nc at 0
rank1 is leaving 2.nc at 1
rank1 is touching 3.nc at 1
rank0 is leaving 3.nc at 0
rank1 is leaving 3.nc at 1
rank0 is touching 0.nc at 2
rank1 is touching 0.nc at 3
rank0 is leaving 0.nc at 2
rank0 is touching 1.nc at 2
rank1 is leaving 0.nc at 3
rank1 is touching 1.nc at 3
rank0 is leaving 1.nc at 2
rank0 is touching 2.nc at 2
rank1 is leaving 1.nc at 3
rank1 is touching 2.nc at 3
rank0 is leaving 2.nc at 2
rank0 is touching 3.nc at 2
rank1 is leaving 2.nc at 3
rank1 is touching 3.nc at 3
rank0 is leaving 3.nc at 2
rank1 is leaving 3.nc at 3
rank1 is touching 0.nc at 4
^CTraceback (most recent call last):
  File "/home/modabao/test.py", line 40, in <module>
    pool.map(func, range(5))
  File "/home/modabao/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 636, in __exit__
    self.shutdown(wait=True)
  File "/home/modabao/miniconda3/lib/python3.8/site-packages/mpi4py/futures/pool.py", line 179, in shutdown
    self._pool.join()
  File "/home/modabao/miniconda3/lib/python3.8/site-packages/mpi4py/futures/_lib.py", line 136, in join
    self.thread.join()
  File "/home/modabao/miniconda3/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/modabao/miniconda3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/modabao/miniconda3/lib/python3.8/site-packages/mpi4py/futures/_lib.py", line 102, in join_threads
    thread.join()
  File "/home/modabao/miniconda3/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/modabao/miniconda3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

I build and install
```
openmpi-v4.1.x-202101230334-4421fce
zlib-1.2.11
hdf5-1.12.0
netcdf-c-4.7.4
mpi4py-3.0.3
netcdf4-python-1.5.5rel2
```
vi
```shell
$ tar -zxf openmpi-v4.1.x-202101230334-4421fce.tar.gz
$ cd openmpi-v4.1.x-202101230334-4421fce
$ ./configure --prefix=/usr/local/openmpi
$ make all
$ sudo make install

$ tar -zxf zlib-1.2.11.tar.gz
$ cd zlib-1.2.11
$ # Build and install zlib
$ ZDIR=/usr/local
$ ./configure --prefix=${ZDIR}
$ make check
$ sudo make install  # or sudo make install, if root permissions required

$ tar -zxf hdf5-1.12.0.tar.gz
$ cd hdf5-1.12.0
$ # Build and install HDF5 with parallel support
$ H5DIR=/usr/local
$ CC=mpicc ./configure --enable-parallel --prefix=${H5DIR} --with-zlib=${ZDIR} --enable-hl
$ make  # check
$ sudo make install

$ tar -zxf netcdf-c-4.7.4.tar.gz
$ cd netcdf-c-4.7.4
$ NCDIR=/usr/local
$ # Build, test, and install netCDF-4 with HDF5 parallel support
$ CC=mpicc CPPFLAGS='-I${H5DIR}/include -I${ZDIR}/include' LDFLAGS='-L${H5DIR}/lib -L${ZDIR}/lib' \
  ./configure --prefix=${NCDIR} --disable-dap
$ make  check
$ sudo make install

$ tar -zxf mpi4py-3.0.3.tar.gz
$ cd mpi4py-3.0.3
$ python setup.py build --mpi=openmpi
$ python setup.py install

$ tar -zxf netcdf4-python-1.5.5rel2.tar.gz
$ cd netcdf4-python-1.5.5rel2
$ python setup.py build  # with setup.cfg modified
$ python setup.py install
```
with
```
MPI_DIR=/usr/local/openmpi
export LD_LIBRARY_PATH=$MPI_DIR/lib:$LD_LIBRARY_PATH
export PATH=$PATH:$MPI_DIR/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
```

I want to write nc files with unlimited dimensions in parallelization, please help.T_T

**Comment by jswhit** [comment]
I think the problem is that your are trying to open and write to the same file on multiple MPI ranks.   You either need to deal with just one file on each rank, or open the same file on all the ranks simultaneously.  Trying to open and write to the same file on different ranks is a no-no.
