### ISSUE TITLE
Can't install or build on M1 Mac

### ISSUE THREAD

**Issue by droffsite** [Unidata/netcdf4-python#1091]
I've had no luck so far getting netcdf4-python installed on my M1 Mac (Big Sur 11.2.2). I'm using miniforge3 looking for ARM versions of packages.

Installed HDF5 and netCDF via brew: brew install hdf5 netcdf

Tried installing under python 3.9 but saw no targets defined for that. Installed python 3.8 
   brew install sashkab/python/python@3.8
and and created (and activated) a Conda environment
  conda install -y python=3.8
  conda create -n myEnv python=3.8 anaconda
  conda create -n myEnv python=3.8 conda

Pip gives no love
```
(myEnv) netcdf4-python % pip install netcdf4      
Collecting netcdf4
  Downloading netCDF4-1.5.6.tar.gz (763 kB)
     |████████████████████████████████| 763 kB 1.5 MB/s 
    ERROR: Command errored out with exit status -9:
     command: /opt/miniforge3/envs/pyNISTView/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fh/l92w0wc979b9kq4w837b2jxr0000gn/T/pip-install-jrieovjp/netcdf4_c5509611feea4b75939901f36a1f0c84/setup.py'"'"'; __file__='"'"'/private/var/folders/fh/l92w0wc979b9kq4w837b2jxr0000gn/T/pip-install-jrieovjp/netcdf4_c5509611feea4b75939901f36a1f0c84/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fh/l92w0wc979b9kq4w837b2jxr0000gn/T/pip-pip-egg-info-mh_ealah
         cwd: /private/var/folders/fh/l92w0wc979b9kq4w837b2jxr0000gn/T/pip-install-jrieovjp/netcdf4_c5509611feea4b75939901f36a1f0c84/
    Complete output (4 lines):
    Package hdf5 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `hdf5.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'hdf5' found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/79/0d/caa957cc1b42b718ce4b9b3e849e6f7aa99faad2d522d8f2d7a33500fba0/netCDF4-1.5.6.tar.gz#sha256=7577f4656af8431b2fa6b6797acb45f81fa1890120e9123b3645e14765da5a7c (from https://pypi.org/simple/netcdf4/). Command errored out with exit status -9: python setup.py egg_info Check the logs for full command output.
  Downloading netCDF4-1.5.5.1.tar.gz (793 kB)
     |████████████████████████████████| 793 kB 17.6 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /opt/miniforge3/envs/pyNISTView/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fh/l92w0wc979b9kq4w837b2jxr0000gn/T/pip-install-jrieovjp/netcdf4_3474e9b050d44a5ca38dabbf1ba2c8dd/setup.py'"'"'; __file__='"'"'/private/var/folders/fh/l92w0wc979b9kq4w837b2jxr0000gn/T/pip-install-jrieovjp/netcdf4_3474e9b050d44a5ca38dabbf1ba2c8dd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fh/l92w0wc979b9kq4w837b2jxr0000gn/T/pip-pip-egg-info-x3foo60v
         cwd: /private/var/folders/fh/l92w0wc979b9kq4w837b2jxr0000gn/T/pip-install-jrieovjp/netcdf4_3474e9b050d44a5ca38dabbf1ba2c8dd/
    Complete output (29 lines):
    Package hdf5 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `hdf5.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'hdf5' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fh/l92w0wc979b9kq4w837b2jxr0000gn/T/pip-install-jrieovjp/netcdf4_3474e9b050d44a5ca38dabbf1ba2c8dd/setup.py", line 401, in <module>
        _populate_hdf5_info(dirstosearch, inc_dirs, libs, lib_dirs)
      File "/private/var/folders/fh/l92w0wc979b9kq4w837b2jxr0000gn/T/pip-install-jrieovjp/netcdf4_3474e9b050d44a5ca38dabbf1ba2c8dd/setup.py", line 356, in _populate_hdf5_info
        raise ValueError('did not find HDF5 headers')
    ValueError: did not find HDF5 headers
    reading from setup.cfg...
    using nc-config...
    checking /opt/homebrew/Cellar/netcdf/4.7.4_2/include ...
    hdf5 headers not found in /opt/homebrew/Cellar/netcdf/4.7.4_2/include
    nc-config did provide path to HDF5 headers, search standard locations...
        HDF5_DIR environment variable not set, checking some standard locations ..
    checking /Users/rmoraski/include ...
    hdf5 headers not found in /Users/rmoraski/include
    checking /usr/local/include ...
    hdf5 headers not found in /usr/local/include
    checking /sw/include ...
    hdf5 headers not found in /sw/include
    checking /opt/include ...
    hdf5 headers not found in /opt/include
    checking /opt/local/include ...
    hdf5 headers not found in /opt/local/include
    checking /usr/include ...
    hdf5 headers not found in /usr/include
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9f/e2/686d0d937f979e7ee0eb6bb4821448da6d2910789f4928c12b070f424b6a/netCDF4-1.5.5.1.tar.gz#sha256=d957e55a667d1fc651ddef22fea10ded0f142b7d9dbbf4d08c0012d32f445abd (from https://pypi.org/simple/netcdf4/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Error -9 for the latest, error 1 for each subsequent version.

On to trying to build from source.

  git clone https://github.com/Unidata/netcdf4-python.git
  cd netcdf4-python

```
  (myEnv) netcdf4-python % python setup.py build
  reading from setup.cfg...
  Package hdf5 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `hdf5.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'hdf5' found
  using nc-config...
  checking /opt/homebrew/Cellar/netcdf/4.7.4_2/include ...
  hdf5 headers not found in /opt/homebrew/Cellar/netcdf/4.7.4_2/include
  nc-config did provide path to HDF5 headers, search standard locations...
      HDF5_DIR environment variable not set, checking some standard locations ..
  checking /opt/miniforge3/envs/pyNISTView/include ...
  HDF5 library version: 1.10.6 headers found in /opt/miniforge3/envs/myEnv/include
  HDF5 library version: 1.10.6 found in /opt/miniforge3/envs/myEnv
  zsh: killed     python setup.py build
```

Adding some prints shows the script giving up somewhere around line 383

  libs.extend(['hdf5_hl', 'hdf5'])

Help!

**Comment by jswhit** [comment]
I guess there are no arm binary packages.  You'll have to build from source, which means you'll need to have the C libs first (hdf5, netcdf, curl etc)

**Comment by droffsite** [comment]
Thanks for the reply.

Am I mistaken in believing that the brew packages (for hdf5, netcdf, and curl) include the C libs?

**Comment by jswhit** [comment]
Yes, they do. I don't know why your install fails after setup.py finds the hdf5 libs.

**Comment by droffsite** [comment]
Is there some additional information I can provide to try to narrow this down?

**Comment by jswhit** [comment]
I don't see any error message from python - instead it looks like the shell is killing your python process?    Maybe try a different shell?

**Comment by droffsite** [comment]
Just got back to working on this. Found the below in ~/Library/Logs/DiagnosticReports.

`Process:               python3.8 [73851]
Path:                  /opt/miniforge3/*/python3.8
Identifier:            python3.8
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        zsh [64055]
Responsible:           Terminal [59091]
User ID:               501

Date/Time:             2021-03-19 14:17:48.867 -0700
OS Version:            macOS 11.2.3 (20D91)
Report Version:        12
Anonymous UUID:        82B278D5-CA4D-F28A-B010-C8A1A6D94FE1

Sleep/Wake UUID:       D0997BFD-6984-4A46-B746-9446253B6D02

Time Awake Since Boot: 81000 seconds
Time Since Wake:       1300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x0000000101370000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2`

**Comment by droffsite** [comment]
Based on the above, I've tried using Apple's python. Getting farther along, but stumbling on the below, where the build is apparently trying to compile for x86 when it should be for arm.

```
clang -bundle -undefined dynamic_lookup -L/usr/local/lib -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk build/temp.macosx-11-x86_64-3.9/src/netCDF4/_netCDF4.o -L/opt/homebrew/Cellar/netcdf/4.7.4_2/lib -L/opt/local/lib -L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite/lib -L/opt/homebrew/Cellar/netcdf/4.7.4_2/lib -L/opt/local/lib -lnetcdf -lhdf5_hl -lhdf5 -o build/lib.macosx-11-x86_64-3.9/netCDF4/_netCDF4.cpython-39-darwin.so
ld: warning: ignoring file /opt/homebrew/Cellar/netcdf/4.7.4_2/lib/libnetcdf.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/local/lib/libhdf5_hl.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/local/lib/libhdf5.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```

**Comment by droffsite** [comment]
Finally solved this today.

I blew away my Miniforge install and started over (brew install miniforge). Installed other packages, 

Once again followed the install instructions, once again crashed after finding the hdf5 library (just as above).

Took a moment to install openCV compiled from source. When testing that python (brew version 3.9) crashed. Checked the logs and saw an issue with szip, then later libtasn1. Reinstalled both (brew reinstall szip libtasn1).

Rechecked the crash log for the netCDF build and saw szip was an issue there. Tried again after the above reinstall and now have a functional netCDF installation.

Apparently I had a b0rked szip and libtasn1.
