### ISSUE TITLE
NetCDF: String match to name in use

### ISSUE THREAD

**Issue by lixysherry** [Unidata/netcdf4-python#1132]
* the version of the software with which you are encountering an issue
>>> import netCDF4 as ncf
>>> print(ncf.__version__)
1.5.7
>>> print(ncf.getlibversion())
4.7.4 of Jun 21 2021 17:36:54 $
Xarray version:  0.19.0

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20)
Linux 3.10.0-1160.31.1.el7.x86_64 #1 

* a description of the issue with the steps needed to reproduce it
* Code to reproduce
import xarray as xr
obs_path = "/home/lix275/data/obs/NRCAN/tasmax/"
drmax = xr.open_dataset(obs_path+"anusplin_tasmax_final.nc")
drmax['tasmax'].to_netcdf(obs_path + "tasmax_final.nc")

* Output and Error from commands:
Traceback (most recent call last):
  File "/home/lix275/code/CMIP6/tas/tasobs.py", line 15, in <module>
    drmax['tasmax'].to_netcdf(obs_path + "tasmax_final.nc")
  File "/home/lix275/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/core/dataarray.py", line 2822, in to_netcdf
    return dataset.to_netcdf(*args, **kwargs)
  File "/home/lix275/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/core/dataset.py", line 1910, in to_netcdf
    invalid_netcdf=invalid_netcdf,
  File "/home/lix275/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/backends/api.py", line 1078, in to_netcdf
    dataset, store, writer, encoding=encoding, unlimited_dims=unlimited_dims
  File "/home/lix275/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/backends/api.py", line 1124, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/home/lix275/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/backends/common.py", line 267, in store
    variables, check_encoding_set, writer, unlimited_dims=unlimited_dims
  File "/home/lix275/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/backends/common.py", line 305, in set_variables
    name, v, check, unlimited_dims=unlimited_dims
  File "/home/lix275/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 501, in prepare_variable
    nc4_var.setncatts(attrs)
  File "src/netCDF4/_netCDF4.pyx", line 4151, in netCDF4._netCDF4.Variable.setncatts
  File "src/netCDF4/_netCDF4.pyx", line 1645, in netCDF4._netCDF4._set_att
  File "src/netCDF4/_netCDF4.pyx", line 1927, in netCDF4._netCDF4._ensure_nc_success
AttributeError: NetCDF: String match to name in use

It fails in the processes of writing. The same error occurs when I copy the Dataset, assign a new name and save it to the NC file. The code is shown below.

drobs = drmax['tasmax'].copy(deep = True)
drobsname = drobs.to_dataset(name='Tmax')
drobsname.to_netcdf(obs_path + "ctasmax_final.nc")

Dimensions:  (lat: 510, lon: 1068, time: 2)
Coordinates:
  * lat      (lat) float64 41.04 41.12 41.21 41.29 ... 83.21 83.29 83.37 83.46
  * lon      (lon) float64 -141.0 -140.9 -140.8 -140.7 ... -52.21 -52.13 -52.04
  * time     (time) datetime64[ns] 1950-01-01 1950-01-02
Data variables:
    Tmax     (time, lat, lon) float32 ...

The data I used is uploaded as below.
[anusplin_tasmax_final.zip](https://github.com/Unidata/netcdf4-python/files/7280484/anusplin_tasmax_final.zip)

* Expected Output
A new file created/written in (default) NETCDF4 format with contents of the Dataset. 
Thank you for any insights here.

**Comment by jswhit** [comment]
I believe this is a duplicate of https://github.com/Unidata/netcdf4-python/issues/1020.  The basic problem is that `NAME` and `CLASS` are reserved attributes in HDF5 and cannot be used/modified by client code.

**Comment by lixysherry** [comment]
Thanks for the quick response. That's pretty helpful!
