### ISSUE TITLE
netCDF4 installed cannot import

### ISSUE THREAD

**Issue by JWGits** [Unidata/netcdf4-python#1133]
Hi,

I'm on my universities HPC that uses Linux 8.3.

I've installed netCDF4 using Conda 4.9.2. I checked if netCDF4 was installed within the active environment using
`nc-config --version` which results in: 

> `netCDF 4.6.1`

When I send the job off I get the following error:

> `Traceback (most recent call last):
>   File "test.py", line 1, in <module>
>     import netCDF4 as nc
> ModuleNotFoundError: No module named 'netCDF4'
> srun: error: cn27: task 0: Exited with exit code 1
> `

Other package are imported as normal in my python script.

Here are the current packages in my environment: 
```
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                        main
> _openmp_mutex             4.5                       1_gnu
> blas                      1.0                         mkl
> bottleneck                1.3.2            py39hdd57654_1
> c-ares                    1.17.1               h27cfd23_0
> ca-certificates           2021.7.5             h06a4308_1
> certifi                   2021.5.30        py39h06a4308_0
> cftime                    1.5.0            py39h6323ea4_0
> curl                      7.78.0               h1ccaba5_0
> hdf4                      4.2.13               h3ca952b_2
> hdf5                      1.10.6               hb1b8bf9_0
> intel-openmp              2021.3.0          h06a4308_3350
> jpeg                      9d                   h7f8727e_0
> krb5                      1.19.2               hac12032_0
> ld_impl_linux-64          2.35.1               h7274673_9
> libcurl                   7.78.0               h0b77cf5_0
> libedit                   3.1.20210714         h7f8727e_0
> libev                     4.33                 h7f8727e_1
> libffi                    3.3                  he6710b0_2
> libgcc-ng                 9.3.0               h5101ec6_17
> libgfortran-ng            7.5.0               ha8ba4b0_17
> libgfortran4              7.5.0               ha8ba4b0_17
> libgomp                   9.3.0               h5101ec6_17
> libnetcdf                 4.6.1                h2053bdc_4
> libnghttp2                1.41.0               hf8bcb03_2
> libssh2                   1.9.0                h1ba5d50_1
> libstdcxx-ng              9.3.0               hd4cf53a_17
> mkl                       2021.3.0           h06a4308_520
> mkl-service               2.4.0            py39h7f8727e_0
> mkl_fft                   1.3.0            py39h42c9631_2
> mkl_random                1.2.2            py39h51133e4_0
> ncurses                   6.2                  he6710b0_1
> netcdf4                   1.5.7            py39he70f4c8_0
> numexpr                   2.7.3            py39h22e1b3c_1
> numpy                     1.20.3           py39hf144106_0
> numpy-base                1.20.3           py39h74d4b33_0
> openssl                   1.1.1l               h7f8727e_0
> pandas                    1.3.3            py39h8c16a72_0
> pip                       21.2.4           py37h06a4308_0
> python                    3.9.7                h12debd9_1
> python-dateutil           2.8.2              pyhd3eb1b0_0
> pytz                      2021.1             pyhd3eb1b0_0
> readline                  8.1                  h27cfd23_0
> setuptools                58.0.4           py39h06a4308_0
> six                       1.16.0             pyhd3eb1b0_0
> sqlite                    3.36.0               hc218d9a_0
> tk                        8.6.11               h1ccaba5_0
> tzdata                    2021a                h5d7bf9c_0
> wheel                     0.37.0             pyhd3eb1b0_1
> xz                        5.2.5                h7b6447c_0
> zlib                      1.2.11               h7b6447c_3
```

Any suggestions?

Thanks!
Jon

**Comment by JWGits** [comment]
Interesting it will complete from the command line with the environment activated

However, I added `conda list` before `srun python3 test.py` in my sbatch script and the full list of packages are printed to the output file from the job running on a compute node. So if that is true it would have to be something related specifically to srun? Here's that output:

```
# packages in environment at /home/jw2636/.conda/envs/mmip:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
blas                      1.0                         mkl  
bottleneck                1.3.2            py39hdd57654_1  
c-ares                    1.17.1               h27cfd23_0  
ca-certificates           2021.7.5             h06a4308_1  
certifi                   2021.5.30        py39h06a4308_0  
cftime                    1.5.0            py39h6323ea4_0  
curl                      7.78.0               h1ccaba5_0  
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.10.6               hb1b8bf9_0  
intel-openmp              2021.3.0          h06a4308_3350  
jpeg                      9d                   h7f8727e_0  
krb5                      1.19.2               hac12032_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libcurl                   7.78.0               h0b77cf5_0  
libedit                   3.1.20210714         h7f8727e_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libnetcdf                 4.6.1                h2053bdc_4  
libnghttp2                1.41.0               hf8bcb03_2  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.3.0               hd4cf53a_17  
mkl                       2021.3.0           h06a4308_520  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.0            py39h42c9631_2  
mkl_random                1.2.2            py39h51133e4_0  
ncurses                   6.2                  he6710b0_1  
netcdf4                   1.5.7            py39he70f4c8_0  
numexpr                   2.7.3            py39h22e1b3c_1  
numpy                     1.20.3           py39hf144106_0  
numpy-base                1.20.3           py39h74d4b33_0  
openssl                   1.1.1l               h7f8727e_0  
pandas                    1.3.3            py39h8c16a72_0  
pip                       21.2.4           py37h06a4308_0  
python                    3.9.7                h12debd9_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
pytz                      2021.1             pyhd3eb1b0_0  
readline                  8.1                  h27cfd23_0  
setuptools                58.0.4           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.36.0               hc218d9a_0  
tk                        8.6.11               h1ccaba5_0  
tzdata                    2021a                h5d7bf9c_0  
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import netCDF4 as nc
ModuleNotFoundError: No module named 'netCDF4'
srun: error: cn26: task 0: Exited with exit code 1
```

I was exploring the Issues posts today and I was thinking it might be similar to #286 but I'm out of my depth. Thanks!

**Comment by JWGits** [comment]
The problem has magically resolved itself today so it is definitely a cluster issue and not likely netcdf4-python. Sorry to bother and thank you for your time!
