### ISSUE TITLE
Error installing on windows with python 3.7

### ISSUE THREAD

**Issue by fakufaku** [Unidata/netcdf4-python#1185]
The pip installation fails on windows with python 3.7. The error is available in [the CI output here](https://github.com/LCAV/pyroomacoustics/runs/7976544639?check_suite_focus=true)

I suspect the reason is that a compiled wheel is not available for netcdf4-python 1.6.0 and python 3.7 on windows (similar to some other issues). Are there plans to make one available ?

* the version of the software with which you are encountering an issue
```
netCDF4-python 1.6.0
```
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
```
python 3.7
windows
```
* a description of the issue with the steps needed to reproduce it

The installation fails with the following message.
```
Collecting netcdf4
  Downloading netCDF4-1.6.0.tar.gz (774 kB)
     -------------------------------------- 774.2/774.2 kB 6.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [25 lines of output]
  reading from setup.cfg...
  
      HDF5_DIR environment variable not set, checking some standard locations ..
  checking C:\Users\runneradmin\include ...
  hdf5 headers not found in C:\Users\runneradmin\include
  checking /usr/local\include ...
  hdf5 headers not found in /usr/local\include
  checking /sw\include ...
  hdf5 headers not found in /sw\include
  checking /opt\include ...
  hdf5 headers not found in /opt\include
  checking /opt/local\include ...
  hdf5 headers not found in /opt/local\include
  checking /opt/homebrew\include ...
  hdf5 headers not found in /opt/homebrew\include
  checking /usr\include ...
  hdf5 headers not found in /usr\include
  Traceback (most recent call last):
    File "<string>", line 36, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-install-7tjlge3x\netcdf4_5ccf66d1b67b491bb55f5ce19a3e85b2\setup.py", line 444, in <module>
      _populate_hdf5_info(dirstosearch, inc_dirs, libs, lib_dirs)
    File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-install-7tjlge3x\netcdf4_5ccf66d1b67b491bb55f5ce19a3e85b2\setup.py", line 385, in _populate_hdf5_info
Error:       raise ValueError('did not find HDF5 headers')
  ValueError: did not find HDF5 headers
  [end of output]
```

**Comment by jswhit** [comment]
if you're on windows 3.7 you're stuck with netcdf4-python 1.5.8.  The windows wheels come from https://www.lfd.uci.edu/~gohlke/pythonlibs/, and only the last three python releases are supported.

**Comment by fakufaku** [comment]
Thanks for taking the time to clarify! We can do a workaround and install 1.5.8 for python 3.7 on windows.
