### ISSUE TITLE
Unable to read OpenDAP with 1.6.4, manual creation of ~/.esg required

### ISSUE THREAD

**Issue by BSchilperoort** [Unidata/netcdf4-python#1278]
System info:

- OS: Linux Mint
- Python version: 3.10
- python-netCDF4 version: 1.6.4

<hr>

When trying to read an OpenDAP url with netCDF4==1.6.4, I get the following error:
```sh
Cookie file cannot be read and written: /home/username/.esg/.dods_cookies
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/netCDF4/_netCDF4.pyx", line 2464, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2027, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -37] NetCDF: Write to read only: 'http://iridl.ldeo.columbia.edu/SOURCES/.OSU/.PRISM/.monthly/dods'
```

It worked fine in 1.6.2.

**However,** when creating the folder `~/.esg`, the OpenDAP dataset loaded in fine. in 1.6.4.

Used code:

```py
import netCDF4
dataset = netCDF4.Dataset("http://iridl.ldeo.columbia.edu/SOURCES/.OSU/.PRISM/.monthly/dods")
```

**Comment by jswhit** [comment]
did you install both 1.6.2 and 1.6.4 via pip (using binary wheels)?

**Comment by BSchilperoort** [comment]
Yes, they were both installed using pip, which grabbed the binary wheels.

**Comment by jswhit** [comment]
it's an issue with netcdf-c 4.9.2, which is used in the 1.6.4 wheel.
