### ISSUE TITLE
HDF5 Headers error using pip install

### ISSUE THREAD

**Issue by e22tracey** [Unidata/netcdf4-python#1281]
Trying to install netCDF4 to a fresh python 3.12.0 install and getting ValueError: did not find HDF5 headers.

Full output below:

```python
python -m pip install netCDF4
Defaulting to user installation because normal site-packages is not writeable
Collecting netCDF4
  Using cached netCDF4-1.6.4.tar.gz (778 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      reading from setup.cfg...

          HDF5_DIR environment variable not set, checking some standard locations ..
      checking C:\Users\e.tracey\include ...
      hdf5 headers not found in C:\Users\e.tracey\include
      checking /usr/local\include ...
      hdf5 headers not found in /usr/local\include
      checking /sw\include ...
      hdf5 headers not found in /sw\include
      checking /opt\include ...
      hdf5 headers not found in /opt\include
      checking /opt/local\include ...
      hdf5 headers not found in /opt/local\include
      checking /opt/homebrew\include ...
      hdf5 headers not found in /opt/homebrew\include
      checking /usr\include ...
      hdf5 headers not found in /usr\include
      Traceback (most recent call last):
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\e.tracey\AppData\Local\Temp\pip-build-env-0ffpf8h1\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\e.tracey\AppData\Local\Temp\pip-build-env-0ffpf8h1\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\e.tracey\AppData\Local\Temp\pip-build-env-0ffpf8h1\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 457, in <module>
        File "<string>", line 398, in _populate_hdf5_info
      ValueError: did not find HDF5 headers
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by jswhit** [comment]
there are no wheels for python 3.12, so pip is trying to build from source.  See https://github.com/Unidata/netcdf4-python/issues/1282

**Comment by jswhit** [comment]
python 3.12 wheels are now available
