### ISSUE TITLE
Install failed - netCDF4 v1.1.4.1

### ISSUE THREAD

**Issue by duytrung** [Unidata/netcdf4-python#343]
Hi all, 
I tried to install netCDF4 v1.1.4.1 but failed
Installation attempted on 23/02/2015:
```
C:\Windows\System32>pip install -U netcdf4
Collecting netcdf4 from https://pypi.python.org/packages/source/n/netCDF4/netCDF4-1.1.4.1.tar.gz#md5
=f261571c595ed37a91a57c9b62695a89
  Downloading netCDF4-1.1.4.1.tar.gz (628kB)
    100% |################################| 630kB 74kB/s
    HDF5_DIR environment variable not set, checking some standard locations ..
    checking C:\Users\My Experiment ...
    checking /usr/local ...
    checking /sw ...
    checking /opt ...
    checking /opt/local ...
    checking /usr ...
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\myexpe~1\appdata\local\temp\pip-build-d3rbaq\netcdf4\setup.py", line 216, in <m
odule>
        raise ValueError('did not find HDF5 headers')
    ValueError: did not find HDF5 headers
    Complete output from command python setup.py egg_info:
    reading from setup.cfg...



    HDF5_DIR environment variable not set, checking some standard locations ..

    checking C:\Users\My Experiment ...

    checking /usr/local ...

    checking /sw ...

    checking /opt ...

    checking /opt/local ...

    checking /usr ...

    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "c:\users\myexpe~1\appdata\local\temp\pip-build-d3rbaq\netcdf4\setup.py", line 216, in <m
odule>

        raise ValueError('did not find HDF5 headers')

    ValueError: did not find HDF5 headers

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in c:\users\myexpe~1\appdata\local\t
emp\pip-build-d3rbaq\netcdf4
```

Regards

**Comment by jswhit** [comment]
Unless you have all the required C libraries installed, I'd recommend using the binary installer for windows at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778417.
