### ISSUE TITLE
ValueError: second must be in 0..59

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf4-python#349]
Python 2.7.9 (default, Dec 11 2014, 02:36:08) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from netCDF4 import date2num, num2date
>>> num2date(1234563.183,'hours since 1452-01-01 01:01:01')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "utils.pyx", line 258, in netCDF4.num2date (netCDF4.c:5669)
  File "/Users/jwhitaker/Library/Python/2.7/lib/python/site-packages/netCDF4-1.1.4-py2.7-macosx-10.9-x86_64.egg/netcdftime/netcdftime.py", line 826, in num2date
    date = DateFromJulianDay(jd, self.calendar)
  File "/Users/jwhitaker/Library/Python/2.7/lib/python/site-packages/netCDF4-1.1.4-py2.7-macosx-10.9-x86_64.egg/netcdftime/netcdftime.py", line 339, in DateFromJulianDay
    minute[0], second[0])
ValueError: second must be in 0..59

**Comment by jswhit** [comment]
fix in pull request #350

**Comment by jswhit** [comment]
fixed by merge of pull request #350
