### ISSUE TITLE
Checking if Dataset is open

### ISSUE THREAD

**Issue by mgoldsborough** [Unidata/netcdf4-python#450]
I'm trying to ensure a Dataset is properly closed in a block of code which occasionally throws exceptions based on sketchy input data (various external web services).  Sometimes, the close method will be invoked twice in a class destructor resulting in this exception:

```
>> file.close()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4/_netCDF4.pyx", line 1728, in netCDF4._netCDF4.Dataset.close (netCDF4/_netCDF4.c:11800)
RuntimeError: NetCDF: Not a valid ID
```

Is there a way to easily check if a dataset is open?

I see there is a *private* attribute called ```_isopen``` on the opened dataset:

```
>>> file = Dataset('/tmp/myfile.nc', 'r')
>>> dir(file)
['__class__', '__delattr__', '__doc__', '__enter__', '__exit__', '__format__', '__getattr__', '__getattribute__', '__getitem__', '__hash__', '__init__', '__new__', '__orthogonal_indexing__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__unicode__', '_enddef', '_grpid', '_isopen', '_redef', 'close', 'cmptypes', 'createCompoundType', 'createDimension', 'createGroup', 'createVLType', 'createVariable', 'data_model', 'delncattr', 'dimensions', 'disk_format', 'file_format', 'filepath', 'getncattr', 'groups', 'keepweakref', 'ncattrs', 'parent', 'path', 'renameAttribute', 'renameDimension', 'renameGroup', 'renameVariable', 'set_auto_mask', 'set_auto_maskandscale', 'set_auto_scale', 'set_fill_off', 'set_fill_on', 'setncattr', 'setncatts', 'sync', 'variables', 'vltypes']
```

And it seems to return 1 for opened and 0 for closed:

```
>>> file = Dataset('/tmp/myfile.nc', 'r')
>>> file._isopen
1
>>> file.close()
>>> file._isopen
0
```

But with it being private, I'd rather not use it.  Any suggestions?  Could this property be exposed in a public method?

Thanks.

**Comment by jswhit** [comment]
see pull request #451

**Comment by jswhit** [comment]
pull request #451 merged, closing now...

**Comment by mgoldsborough** [comment]
This is great.  Thanks, @jswhit!

**Comment by mgoldsborough** [comment]
@jswhit any chance of a version bump to 1.9.3 so it's picked up by pip? Thanks.

**Comment by jswhit** [comment]
version number bumped from 1.1.9 to 1.2.0
