### ISSUE TITLE
String variables cannot be set with masked arrays

### ISSUE THREAD

**Issue by jjhelmus** [Unidata/netcdf4-python#464]
Trying to set the items of a Variable using a masked array raises a TypeError.  For example:

``` Python
import netCDF4
import numpy as np
dset = netCDF4.Dataset('example.nc', 'w', format='NETCDF4')
dset.createDimension('str_length', 2)
var_u = dset.createVariable('var_u', str, ('str_length', ))
test_u = np.ma.zeros((2, ), dtype='U1')
test_u[:] = np.ma.masked
test_u[0] = 'A'
var_u[:] = test_u[:]
```

```
$ python bug.py 
Traceback (most recent call last):
  File "nc_bug.py", line 11, in <module>
    var_u[:] = test_u[:]
  File "netCDF4/_netCDF4.pyx", line 3905, in netCDF4._netCDF4.Variable.__setitem__ (netCDF4/_netCDF4.c:40014)
    self._put(dataput,a,b,c)
  File "netCDF4/_netCDF4.pyx", line 4130, in netCDF4._netCDF4.Variable._put (netCDF4/_netCDF4.c:41918)
    strdata[i] = data[i]
TypeError: expected string or Unicode object, MaskedConstant found
```

PR to address this will be submitted shortly.

**Comment by jswhit** [comment]
pull request #469 has been merged - an error message is now raised when masked arrays are assigned to vlen str slices.

**Comment by jjhelmus** [comment]
Thanks for fixing this @jswhit
