### ISSUE TITLE
'python setup.py install'  failure with Anaconda python on ubuntu14.04

### ISSUE THREAD

**Issue by sherylwang** [Unidata/netcdf4-python#472]
Hello,everyone
I'm trying to install netcdf4-python on ubuntu14.04, but failed.
The hdf5 and netcdf4 have been  installed through apt-get : sudo apt-get install libhdf5-serial-dev libnetcdf-dev. The environment variable USENCCONFIG have already been set to 1.
I've  downloaded the netcdf4-python through  Github. The 'python setup.py build' passed successfully, while 'python setup.py install' failured. The python 2.7 on my computer is an Anaconda version.

The error is like this:

cython version 0.22.1 found ...
reading from setup.cfg...
using nc-config ...
using netcdf library version 4.3.3
using Cython to compile netCDF4.pyx...
netcdf lib has group rename capability
netcdf lib has nc_inq_path function
netcdf lib has nc_inq_format_extended function
Compiling netCDF4/_netCDF4.pyx because it changed.
Cythonizing netCDF4/_netCDF4.pyx
running install
Traceback (most recent call last):
  File "setup.py", line 442, in <module>
    **setuptools_extra_kwargs)
  File "/home/xiaqing/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/xiaqing/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/xiaqing/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 82, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
  File "/home/xiaqing/anaconda/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 274, in finalize_options
    ('install_dir','install_dir')
  File "/home/xiaqing/anaconda/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/home/xiaqing/anaconda/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 13, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/home/xiaqing/anaconda/lib/python2.7/distutils/cmd.py", line 302, in set_undefined_options
    getattr(src_cmd_obj, src_option))
  File "/home/xiaqing/anaconda/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
    raise AttributeError, attr
AttributeError: install_layout

Hopes someone can help me.

**Comment by shoyer** [comment]
Have you tried installing the `netcdf4` package distributed by Anaconda? `conda install netcdf4` should do it.

**Comment by sherylwang** [comment]
Many thanks for shoyer's suggestion. The problem is solved!

**Comment by jswhit** [comment]
Updating setuptools might also have fixed it.
