### ISSUE TITLE
Undefined nc_xxx symbols in _netCDF4.so

### ISSUE THREAD

**Issue by sloede** [Unidata/netcdf4-python#512]
After compilation of netcdf4-python against netCDF 4.4.0, I always get the following error when running `python tests/run_all.py`:
```
Traceback (most recent call last):
  File "test/run_all.py", line 1, in <module>
    import glob, os, sys, unittest, netCDF4
  File "build/bdist.linux-x86_64/egg/netCDF4/__init__.py", line 3, in <module>
    # $Id$
  File "build/bdist.linux-x86_64/egg/netCDF4/_netCDF4.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/netCDF4/_netCDF4.py", line 6, in __bootstrap__
ImportError: /home/mic/.python-eggs/netCDF4-1.2.2-py2.7-linux-x86_64.egg-tmp/netCDF4/_netCDF4.so: undefined symbol: nc_inq_var_endian
```
When I call `ldd /home/mic/.python-eggs/netCDF4-1.2.2-py2.7-linux-x86_64.egg-tmp/netCDF4/_netCDF4.so`, there is in fact no mention of any netcdf library, and `nm /home/mic/.python-eggs/netCDF4-1.2.2-py2.7-linux-x86_64.egg-tmp/netCDF4/_netCDF4.so | grep nc_` confirms that there are a lot of unresolved `nc_...` symbols.

Only when I call `setup.py` with the following command, 
```
LDFLAGS="-lnetcdf" python setup.py build
```
and then install it, the error above disappears and all tests pass (except the diskless test, which is OK for me). Either I am too stupid to do the compilation right or there seems to be a bug in the build scripts. Any ideas?

**Comment by jswhit** [comment]
Please remove your build directory, run ``python setup.py build`` again, and post the full output.

**Comment by sloede** [comment]
Note: the additional linker flags are due to the fact that netCDF and HDF5 are installed to non-standard locations.

**Build command**
```
 LDFLAGS="-L/pds/opt/netcdf-4.4.0/lib64 -Wl,-rpath,/pds/opt/netcdf-4.4.0/lib64 -Wl,-rpath,/pds/opt/hdf5/lib64" python setup.py build
```

**Build output**
```
reading from setup.cfg...
Package netcdf was not found in the pkg-config search path.
Perhaps you should add the directory containing `netcdf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'netcdf' found
using nc-config ...
Package netcdf was not found in the pkg-config search path.
Perhaps you should add the directory containing `netcdf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'netcdf' found
unable to detect netcdf library versionrunning build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/netcdftime
copying netcdftime/netcdftime.py -> build/lib.linux-x86_64-2.7/netcdftime
copying netcdftime/__init__.py -> build/lib.linux-x86_64-2.7/netcdftime
creating build/lib.linux-x86_64-2.7/netCDF4
copying netCDF4/utils.py -> build/lib.linux-x86_64-2.7/netCDF4
copying netCDF4/__init__.py -> build/lib.linux-x86_64-2.7/netCDF4
running build_ext
building 'netCDF4._netCDF4' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/netCDF4
gcc -pthread -fno-strict-aliasing -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DOPENSSL_LOAD_CONF -fPIC -I/pds/opt/netcdf-4.4.0/include -I/pds/opt/hdf5/include -I/pds/opt/openmpi/include -I/usr/lib64/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c netCDF4/_netCDF4.c -o build/temp.linux-x86_64-2.7/netCDF4/_netCDF4.o
In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from netCDF4/_netCDF4.c:243:
/usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
netCDF4/_netCDF4.c: In function ‘__pyx_f_7netCDF4_8_netCDF4__set_att’:
netCDF4/_netCDF4.c:6125:7: warning: passing argument 5 of ‘nc_put_att_string’ from incompatible pointer type [enabled by default]
       __pyx_v_ierr = nc_put_att_string(__pyx_t_6, __pyx_v_varid, __pyx_v_attname, 1, (&__pyx_v_datstring));
       ^
In file included from netCDF4/_netCDF4.c:242:0:
/pds/opt/netcdf-4.4.0/include/netcdf.h:1002:1: note: expected ‘const char **’ but argument is of type ‘char **’
 nc_put_att_string(int ncid, int varid, const char *name,
 ^
netCDF4/_netCDF4.c: In function ‘__pyx_f_7netCDF4_8_netCDF4__get_types’:
netCDF4/_netCDF4.c:6468:12: warning: ‘__pyx_v_typeids’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   nc_type *__pyx_v_typeids;
            ^
netCDF4/_netCDF4.c: In function ‘__pyx_f_7netCDF4_8_netCDF4__find_cmptype’:
netCDF4/_netCDF4.c:81331:34: warning: ‘__pyx_v_xtype’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             return PyInt_FromLong((long) value);
                                  ^
netCDF4/_netCDF4.c:50940:11: note: ‘__pyx_v_xtype’ was declared here
   nc_type __pyx_v_xtype;
           ^
netCDF4/_netCDF4.c: In function ‘__pyx_pw_7netCDF4_8_netCDF4_8Variable_1__init__’:
netCDF4/_netCDF4.c:27171:20: warning: ‘__pyx_v_dimids’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       __pyx_v_ierr = nc_def_var(__pyx_v_self->_grpid, __pyx_v_varname, __pyx_v_xtype, __pyx_v_ndims, __pyx_v_dimids, (&__pyx_v_self->_varid));
                    ^
netCDF4/_netCDF4.c:25771:8: note: ‘__pyx_v_dimids’ was declared here
   int *__pyx_v_dimids;
        ^
gcc -pthread -shared -L/pds/opt/netcdf-4.4.0/lib64 -Wl,-rpath,/pds/opt/netcdf-4.4.0/lib64 -Wl,-rpath,/pds/opt/hdf5/lib64 build/temp.linux-x86_64-2.7/netCDF4/_netCDF4.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/netCDF4/_netCDF4.so
building 'netcdftime._datetime' extension
creating build/temp.linux-x86_64-2.7/netcdftime
gcc -pthread -fno-strict-aliasing -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DOPENSSL_LOAD_CONF -fPIC -I/usr/include/python2.7 -c netcdftime/_datetime.c -o build/temp.linux-x86_64-2.7/netcdftime/_datetime.o
gcc -pthread -shared -L/pds/opt/netcdf-4.4.0/lib64 -Wl,-rpath,/pds/opt/netcdf-4.4.0/lib64 -Wl,-rpath,/pds/opt/hdf5/lib64 build/temp.linux-x86_64-2.7/netcdftime/_datetime.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/netcdftime/_datetime.so
```

**Contents of `setup.cfg`**
```
[options]
use_ncconfig = True
use_cython = True
ncconfig=/pds/opt/netcdf-4.4.0/bin/nc-config

[directories]
HDF5_dir = /pds/opt/hdf5

[egg_info]
tag_build =
tag_date = 0
tag_svn_revision = 0
```

Thanks for you interest! I hope this helps...

**Comment by jswhit** [comment]
The problem is this:

    using nc-config ...
    Package netcdf was not found in the pkg-config search path.
    Perhaps you should add the directory containing `netcdf.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'netcdf' found
    unable to detect netcdf library version

Apparently nc-config is not working.  setup.py should probably just quit at that point.

You can either try to figure out why nc-config is not working, or edit setup.cfg and manually enter the location of the libraries and headers.

**Comment by sloede** [comment]
Setting up the directories in `setup.cfg` manually does not work either, as it seems like the library directory defaults to `lib/`, whereas netcdf-c installs its libraries to `lib64/`. The following shows the command with which I finally got it work:
```
CPPFLAGS="-I/pds/opt/openmpi/include" \
LDFLAGS="-L/pds/opt/netcdf-4.4.0/lib64 -lnetcdf -Wl,-rpath,/pds/opt/netcdf-4.4.0/lib64 -Wl,-rpath,/pds/opt/openmpi/lib64 -Wl,-rpath,/pds/opt/hdf5/lib64" \
python setup.py build
```

I guess I understand that I have to manually specify the `rpath` for HDF5 since it is not located in a standard location. However, if I include the `rpath` for OpenMPI, which is actually in `LD_LIBRARY_PATH`, I get the following output:
```
Traceback (most recent call last):
  File "run_all.py", line 1, in <module>
    import glob, os, sys, unittest, netCDF4
  File "build/bdist.linux-x86_64/egg/netCDF4/__init__.py", line 3, in <module>
    # $Id$
  File "build/bdist.linux-x86_64/egg/netCDF4/_netCDF4.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/netCDF4/_netCDF4.py", line 6, in __bootstrap__
ImportError: /pds/opt/netcdf-4.4.0/lib64/libnetcdf.so.11: undefined symbol: ompi_mpi_char
```

Is it possible that `LD_LIBRARY_PATH` is not searched when looking for libraries?

P.S.: I opened an issue about the `nc-config` problem under https://github.com/Unidata/netcdf-c/issues/192

**Comment by jswhit** [comment]
don't know about the rpath issue (I though distutils handled that automatically), but I think you probably did not configure setup.cfg correctly.  Did you set use_ncconfig=False?

**Comment by sloede** [comment]
@jswhit as far as I can tell, `setup.cfg` should be ok:
```
[options]
use_ncconfig = False
use_cython = True

[directories]
HDF5_dir = /pds/opt/hdf5
netCDF4_dir = /pds/opt/netcdf-4.4.0

[egg_info]
tag_build =
tag_date = 0
tag_svn_revision = 0
```

I removed all `nc-config`-related configuration after your hint that `nc-config` is indeed not working properly. As for whether distutils handle `rpath` automatically: The problem seems to be again the fact that `setup.py`/distutils assume `lib/` while HDF5/NetCDF install their libraries to `lib64/`. When looking at the output of the build command, the following line is included:
```
gcc -pthread -shared -L/pds/opt/netcdf-4.4.0/lib64 -lnetcdf -Wl,-rpath,/pds/opt/netcdf-4.4.0/lib64 -Wl,-rpath,/pds/opt/openmpi/lib64 -L/pds/opt/hdf5/lib64 -Wl,-rpath,/pds/opt/hdf5/lib64 -I/pds/opt/openmpi/include build/temp.linux-x86_64-2.7/netCDF4/_netCDF4.o -L/pds/opt/netcdf-4.4.0/lib -L/pds/opt/hdf5/lib -L/usr/lib64 -Wl,-R/pds/opt/netcdf-4.4.0/lib -Wl,-R/pds/opt/hdf5/lib -lnetcdf -lhdf5_hl -lhdf5 -lz -lpython2.7 -o build/lib.linux-x86_64-2.7/netCDF4/_netCDF4.so
```

Apparently the flags `-Wl,-R/pds/opt/netcdf-4.4.0/lib -Wl,-R/pds/opt/hdf5/lib` were added automatically, but they refer to non-existent directories. I don't know whether this is a problem of the netcdf4-python package or the distutils themselves. If the latter is the case, please feel free to close this issue.

**Comment by jswhit** [comment]
You can use ``HD5_incdir`` and ``HDF5_libdir``  to set the directories for the includes and libs manually - see the comments in ``setup.cfg``.

**Comment by sloede** [comment]
Alas, you are right. I should RTFM. Sorry about that and thanks for the support!

**Comment by WardF** [comment]
Are HDF_incdir and HDF_libdir provided by the HDF package or determined by netcdf4-python? Is this something the NetCDF C library needs/should provide?

**Comment by sloede** [comment]
In my case I had to manually add them to `setup.cfg`. HDF5 does not seem to have a tool similar to `nc-config`.

**Comment by WardF** [comment]
Thanks; I'll sort out what's going on with nc-config.

**Comment by jswhit** [comment]
nc-config would have provided all the needed information (including the locations of the HDF headers and library) - if it had worked.
