### ISSUE TITLE
ImportError: libmfhdf.so.0: cannot open shared object file (when updating to netcdf4 1.2.4-np111py27_0)

### ISSUE THREAD

**Issue by ajoros** [Unidata/netcdf4-python#574]
Hi all,

I get the  error ImportError:` libmfhdf.so.0: cannot open shared object file: No such file or directory` when my group upgraded netCDF4:
 
```
[root@gridlogin-0-0:/share/apps/gnu/Miniconda-3.7.0]# conda update netcdf4
Fetching package metadata .........
Solving package specifications: ..........
 
Package plan for installation in environment /share/apps/gnu/Miniconda-3.7.0:
 
The following packages will be downloaded:
 
    package                    |            build
    ---------------------------|-----------------
    curl-7.49.0                |                1         543 KB
 
The following packages will be UPDATED:
 
    curl:      7.45.0-0          --> 7.49.0-1
    hdf5:      1.8.15.1-2        --> 1.8.17-0
    libnetcdf: 4.3.3.1-3         --> 4.4.1-0
    netcdf4:   1.2.2-np111py27_0 --> 1.2.4-np111py27_0
```
 
Here is the error when I attempt to execute `from netCDF4 import Dataset`:
```
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from netCDF4 import Dataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Input/WRF_AIC/src/miniconda/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: libmfhdf.so.0: cannot open shared object file: No such file or directory
```

Any help would be appreciated.
Our group has reverted to netcdf4 1.2.2 instead as seen below (although we'd like to use the most up to date version):

```
# packages in environment at /share/apps/gnu/Miniconda-3.7.0:
#
hdf5                      1.8.15.1                      2
netcdf4                   1.2.2               np111py27_0
```

Thanks

**Comment by dopplershift** [comment]
You might try installing hdf4:
```console
conda install hdf4
```
since that's the package that should be providing that library--I'm not sure why things broke suddenly for you.

Otherwise, I'd send a message to the Anaconda mailing list: https://groups.google.com/a/continuum.io/forum/?fromgroups#!forum/anaconda

We don't maintain the netcdf4 package in anaconda/miniconda, so there's not much else we can do.

**Comment by rsignell-usgs** [comment]
@ajoros , did the problematic package come from the defaults channel, or from conda-forge or another channel?

You can type:
```
conda config --set show_channel_urls yes
```
and then you will be able to see what channels your packages came from.
