### ISSUE TITLE
broken install with version 1.2.5.1

### ISSUE THREAD

**Issue by mdklatt** [Unidata/netcdf4-python#617]
Installation into a fresh virtualenv environment on MacOS X fails for version **1.2.5.1**. Pinning the requirement to **1.2.5** allows installation without error.

```
$ venv/bin/pip list


pip (9.0.1)
setuptools (30.3.0)
wheel (0.30.0a0)
```

```
$ venv/bin/pip install netCDF

Collecting netCDF4
  Using cached netCDF4-1.2.5.1.tar.gz
Collecting numpy>=1.7 (from netCDF4)
  Using cached numpy-1.11.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Building wheels for collected packages: netCDF4
  Running setup.py bdist_wheel for netCDF4: started
  Running setup.py bdist_wheel for netCDF4: finished with status 'error'
  Complete output from command venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8t/wjjjmxzn4577vl7055k32r600000gn/T/pip-build-0K7MBF/netCDF4/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/8t/wjjjmxzn4577vl7055k32r600000gn/T/tmpKlKmPOpip-wheel- --python-tag cp27:
  reading from setup.cfg...
  Package hdf5 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `hdf5.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'hdf5' found
  using nc-config ...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/8t/wjjjmxzn4577vl7055k32r600000gn/T/pip-build-0K7MBF/netCDF4/setup.py", line 383, in <module>
      import numpy
  ImportError: No module named numpy
  
  ----------------------------------------
  Failed building wheel for netCDF4
  Running setup.py clean for netCDF4
  Complete output from command venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8t/wjjjmxzn4577vl7055k32r600000gn/T/pip-build-0K7MBF/netCDF4/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  reading from setup.cfg...
  Package hdf5 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `hdf5.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'hdf5' found
  using nc-config ...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/8t/wjjjmxzn4577vl7055k32r600000gn/T/pip-build-0K7MBF/netCDF4/setup.py", line 383, in <module>
      import numpy
  ImportError: No module named numpy
  
  ----------------------------------------
  Failed cleaning build dir for netCDF4
Failed to build netCDF4
Installing collected packages: numpy, netCDF4
  Running setup.py install for netCDF4: started
    Running setup.py install for netCDF4: finished with status 'error'
    Complete output from command venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8t/wjjjmxzn4577vl7055k32r600000gn/T/pip-build-0K7MBF/netCDF4/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/8t/wjjjmxzn4577vl7055k32r600000gn/T/pip-wnKuc7-record/install-record.txt --single-version-externally-managed --compile --install-headers venv/include/site/python2.7/netCDF4:
    reading from setup.cfg...
    Package hdf5 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `hdf5.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'hdf5' found
    using nc-config ...
    using netcdf library version 4.3.3.1
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-intel-2.7
    creating build/lib.macosx-10.11-intel-2.7/netcdftime
    copying netcdftime/__init__.py -> build/lib.macosx-10.11-intel-2.7/netcdftime
    creating build/lib.macosx-10.11-intel-2.7/netCDF4
    copying netCDF4/__init__.py -> build/lib.macosx-10.11-intel-2.7/netCDF4
    copying netCDF4/utils.py -> build/lib.macosx-10.11-intel-2.7/netCDF4
    running build_ext
    building 'netCDF4._netCDF4' extension
    creating build/temp.macosx-10.11-intel-2.7
    creating build/temp.macosx-10.11-intel-2.7/netCDF4
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/usr/local/Cellar/netcdf/4.3.3.1_4/include -Ivenv/lib/python2.7/site-packages/numpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c netCDF4/_netCDF4.c -o build/temp.macosx-10.11-intel-2.7/netCDF4/_netCDF4.o
    netCDF4/_netCDF4.c:296:10: fatal error: 'H5public.h' file not found
    #include "H5public.h"
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8t/wjjjmxzn4577vl7055k32r600000gn/T/pip-build-0K7MBF/netCDF4/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/8t/wjjjmxzn4577vl7055k32r600000gn/T/pip-wnKuc7-record/install-record.txt --single-version-externally-managed --compile --install-headers venv/include/site/python2.7/netCDF4" failed with error code 1 in /private/var/folders/8t/wjjjmxzn4577vl7055k32r600000gn/T/pip-build-0K7MBF/netCDF4/
 ```

**Comment by mdklatt** [comment]
This issue is also present on CentOS 7.2.

**Comment by jswhit** [comment]
I uploaded a new tarball today, with the name changed to 1.2.5.1.  Do I have to create a new release on pypi for this to work?

**Comment by mdklatt** [comment]
@jswhit 

The breaking change happened today. If you uploaded the 1.2.5.1 tarball to pypi, that's what's getting pulled down by pip, and that's what seems to be causing the problem.

**Comment by jswhit** [comment]
Do you know what the naming convention that pip expects is?  Perhaps I could rename to ``netCDF4-1.2.5_src.tar.gz`` (I just can't use ``netCDF4-1.2.5.tar.gz`` again).

**Comment by mdklatt** [comment]
Sorry, I don't know much about how pip interacts with pypi. Are you trying to upload 1.2.5.1 as a fix to 1.2.5, because 1.2.5.1 is where the problem seems to be?

This works for me:
pip install netCDF4==1.2.5

These are both broken for me:
pip install netCDF4  (this grabs 1.2.5.1 as the latest version)
pip install netCDF4==1.2.5.1  (explicitly grab 1.2.5.1)

**Comment by matthew-brett** [comment]
I was trying to build a wheel for 1.2.5.1 but I guess I misunderstood what 1.2.5.1 is - I think there isn't a tag for it in the repo?

If you need to fix a release on pypi, you can use the rather obscure build tag feature of pip - see : https://github.com/h5py/h5py/issues/731#issuecomment-230826012

**Comment by matthew-brett** [comment]
Meanwhile I"m building wheels for the `v1.2.6rel` tag in case that's the next release...

**Comment by mdklatt** [comment]
I think what's going in is that pip is pulling down a tarball for 1.2.5.1 instead of a binary wheel, so that's why the install complains about missing dependencies.

**Comment by jswhit** [comment]
just created a 1.2.6 release, so this should be fixed now.
