### ISSUE TITLE
Can not use NetCDF4 with CGI (undefined symbol: EVP_idea_cbc)

### ISSUE THREAD

**Issue by roipoussiere** [Unidata/netcdf4-python#620]
I use NetCDF4 (installed with Anaconda) in webservice, which require python cgi.

I can successfully import `netCDF4` and `cgi` separately, but when I try to import both of them, I get this error:

```
[Wed Dec 14 17:31:19.178947 2016] [cgi:error] [pid 16816] [client 127.0.0.1:42728] AH01215: Traceback (most recent call last):: /home/roipoussiere/test/test_script.py
[Wed Dec 14 17:31:19.179033 2016] [cgi:error] [pid 16816] [client 127.0.0.1:42728] AH01215:   File "/home/roipoussiere/test/test_script.py", line 45, in <module>: /home/roipoussiere/test/test_script.py
[Wed Dec 14 17:31:19.179093 2016] [cgi:error] [pid 16816] [client 127.0.0.1:42728] AH01215:     import netCDF4: /home/roipoussiere/test/test_script.py
[Wed Dec 14 17:31:19.179151 2016] [cgi:error] [pid 16816] [client 127.0.0.1:42728] AH01215:   File "/home/roipoussiere/.anaconda2/envs/nc2cdf/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>: /home/roipoussiere/test/test_script.py
[Wed Dec 14 17:31:19.179178 2016] [cgi:error] [pid 16816] [client 127.0.0.1:42728] AH01215:     from ._netCDF4 import *: /home/roipoussiere/test/test_script.py
[Wed Dec 14 17:31:19.179247 2016] [cgi:error] [pid 16816] [client 127.0.0.1:42728] AH01215: ImportError: /home/nathanael/.anaconda2/envs/nc2cdf/lib/python2.7/site-packages/netCDF4/../../.././libssl.so.1.0.0: undefined symbol: EVP_idea_cbc: /home/roipoussiere/test/test_script.py
[Wed Dec 14 17:31:19.182312 2016] [cgi:error] [pid 16816] [client 127.0.0.1:42728] End of script output before headers: get_cdf.py
```

**Comment by jswhit** [comment]
the netcdf c library uses libcurl for opendap data access - and libcurl uses the openssl library.  I think you must have more than one openssl library installed on your system and the one you are using at runtime inside the webservice environment is not the right one.

**Comment by jswhit** [comment]
Any update on this?

**Comment by roipoussiere** [comment]
Yep, indeed `import netCDF4` must be placed before all other imports, that fixes the problem. Thank you.
