### ISSUE TITLE
netCDF4 1.2.5 and 1.2.6 fail to read file that works with 1.2.4

### ISSUE THREAD

**Issue by cpaulik** [Unidata/netcdf4-python#624]
To reproduce:
Put
```
import netCDF4 as nc4
print(nc4.__version__)
ds = nc4.Dataset('TUW_ERS_AMI_SSM_WARP55R11_1395.nc')
print(ds.variables['sm'][134])
```
as `nctest.py` and the file hosted at https://github.com/TUW-GEO/pytesmo-test-data/blob/master/sat/ers/55R11/TUW_ERS_AMI_SSM_WARP55R11_1395.nc

in the same folder. Then:

```
(miniconda-3.16.0) ❯ conda create -n netcdf4-debugging -c conda-forge netcdf4
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/cpa/.pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging:

The following NEW packages will be INSTALLED:

    ca-certificates: 2016.9.26-0       conda-forge
    certifi:         2016.9.26-py27_0  conda-forge
    curl:            7.49.1-2          conda-forge
    hdf4:            4.2.12-0          conda-forge
    hdf5:            1.8.17-8          conda-forge
    jpeg:            9b-0              conda-forge
    libgfortran:     3.0.0-1           defaults   
    libnetcdf:       4.4.1.1-1         conda-forge
    mkl:             11.3.3-0          defaults   
    ncurses:         5.9-10            conda-forge
    netcdf4:         1.2.6-np111py27_0 conda-forge
    numpy:           1.11.2-py27_0     defaults   
    openssl:         1.0.2h-3          conda-forge
    pip:             9.0.1-py27_0      conda-forge
    python:          2.7.12-1          conda-forge
    readline:        6.2-0             conda-forge
    setuptools:      32.1.0-py27_0     conda-forge
    sqlite:          3.13.0-1          conda-forge
    tk:              8.5.19-1          conda-forge
    wheel:           0.29.0-py27_0     conda-forge
    zlib:            1.2.8-3           conda-forge

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#############################################################################| 100%
#
# To activate this environment, use:
# > source activate netcdf4-debugging
#
# To deactivate this environment, use:
# > source deactivate netcdf4-debugging
#
                                                                                                     
~/workspace 8s
(miniconda-3.16.0) ❯ source activate netcdf4-debugging 
                                                                                                          
~/workspace
(miniconda-3.16.0/envs/netcdf4-debugging) ❯ python nctest.py 
1.2.6
Traceback (most recent call last):
  File "nctest.py", line 4, in <module>
    print(ds.variables['sm'][134])
  File "netCDF4/_netCDF4.pyx", line 3790, in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:41109)
  File "netCDF4/_netCDF4.pyx", line 3862, in netCDF4._netCDF4.Variable._toma (netCDF4/_netCDF4.c:42749)
ValueError: non-broadcastable output operand with shape () doesn't match the broadcast shape (1,)

~/workspace
(miniconda-3.16.0/envs/netcdf4-debugging) ❯ conda uninstall netCDF4
Fetching package metadata .........
Solving package specifications: ..........

Package plan for package removal in environment /home/cpa/.pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging:

The following packages will be REMOVED:

    netcdf4: 1.2.6-np111py27_0 conda-forge

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|#############################################################################| 100%
                                                                                                          
~/workspace 6s
(miniconda-3.16.0/envs/netcdf4-debugging) ❯ pip install netCDF4==1.2.4
Collecting netCDF4==1.2.4
  Using cached netCDF4-1.2.4-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: numpy>=1.7 in /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages (from netCDF4==1.2.4)
Installing collected packages: netCDF4
Successfully installed netCDF4-1.2.4
                                                                                                          
~/workspace
(miniconda-3.16.0/envs/netcdf4-debugging) ❯ python nctest.py 
1.2.4
52

~/workspace
(miniconda-3.16.0/envs/netcdf4-debugging) ❯ pip uninstall netCDF4
Uninstalling netCDF4-1.2.4:
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/bin/nc3tonc4
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/bin/nc4tonc3
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/bin/ncinfo
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4-1.2.4.dist-info/DESCRIPTION.rst
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4-1.2.4.dist-info/INSTALLER
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4-1.2.4.dist-info/METADATA
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4-1.2.4.dist-info/RECORD
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4-1.2.4.dist-info/WHEEL
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4-1.2.4.dist-info/entry_points.txt
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4-1.2.4.dist-info/metadata.json
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4-1.2.4.dist-info/top_level.txt
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4/.libs/libaec-39ca7337.so.0.0.4
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4/.libs/libcurl-9d6e3ea8.so.4.4.0
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4/.libs/libhdf5-8111cbbb.so.10.2.0
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4/.libs/libhdf5_hl-23bcbad1.so.10.1.0
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4/.libs/libnetcdf-32da214a.so.11.0.3
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4/.libs/libsz-08416a88.so.2.0.1
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4/.libs/libz-a147dcb0.so.1.2.3
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4/__init__.py
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4/__init__.pyc
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4/_netCDF4.so
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4/utils.py
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netCDF4/utils.pyc
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netcdftime/__init__.py
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netcdftime/__init__.pyc
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netcdftime/_datetime.so
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netcdftime/netcdftime.py
  /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages/netcdftime/netcdftime.pyc
Proceed (y/n)? y
  Successfully uninstalled netCDF4-1.2.4
                                                                                                          
~/workspace
(miniconda-3.16.0/envs/netcdf4-debugging) ❯ pip install netCDF4==1.2.5
Collecting netCDF4==1.2.5
  Using cached netCDF4-1.2.5-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: numpy>=1.7 in /data/pyenv/versions/miniconda-3.16.0/envs/netcdf4-debugging/lib/python2.7/site-packages (from netCDF4==1.2.5)
Installing collected packages: netCDF4
Successfully installed netCDF4-1.2.5
                                                                                                          
~/workspace
(miniconda-3.16.0/envs/netcdf4-debugging) ❯ python nctest.py
1.2.5
Traceback (most recent call last):
  File "nctest.py", line 4, in <module>
    print(ds.variables['sm'][134])
  File "netCDF4/_netCDF4.pyx", line 3777, in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:41246)
  File "netCDF4/_netCDF4.pyx", line 3851, in netCDF4._netCDF4.Variable._toma (netCDF4/_netCDF4.c:42886)
ValueError: non-broadcastable output operand with shape () doesn't match the broadcast shape (1,)
```

**Comment by jswhit** [comment]
Fix in pull request #625

**Comment by jswhit** [comment]
pull request #625 merged, so this should be fixed in master now.

**Comment by cpaulik** [comment]
Thank you.
