### ISSUE TITLE
Test failure with python 3.6

### ISSUE THREAD

**Issue by opoplawski** [Unidata/netcdf4-python#626]
Getting this with python 3.6:
```
+ /usr/bin/python3 run_all.py
...E....................................................................................not running tst_unicode.py ...
not running tst_cdf5.py ...
netcdf4-python version: 1.2.6
HDF5 lib version:       1.8.18
netcdf lib version:     4.4.1.1
numpy version           1.11.2
======================================================================
ERROR: runTest (tst_types.PrimitiveTypesTestCase)
testing primitive data type
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/netcdf4-python-1.2.6rel/test/tst_types.py", line 71, in runTest
    assert_array_equal(datfilled,NP.asarray(data._FillValue,datfilled.dtype))
  File "netCDF4/_netCDF4.pyx", line 3705, in netCDF4._netCDF4.Variable.__getattr__ (netCDF4/_netCDF4.c:39217)
  File "netCDF4/_netCDF4.pyx", line 3516, in netCDF4._netCDF4.Variable.getncattr (netCDF4/_netCDF4.c:36467)
  File "netCDF4/_netCDF4.pyx", line 1125, in netCDF4._netCDF4._get_att (netCDF4/_netCDF4.c:4722)
TypeError: only integer arrays with one element can be converted to an index
----------------------------------------------------------------------
```

**Comment by cgohlke** [comment]
I get the same on Windows.

**Comment by jswhit** [comment]
I've included a fix for this in pull request #625. I also modified .travis.yml to test with python 3.6 instead of python 3.3.

**Comment by jswhit** [comment]
pull request #625 merged, so this should be fixed in master now.

**Comment by matthew-brett** [comment]
Any chance of a release, to fix this error?  Just ran into the same when building Python 3.6 wheels:

* https://travis-ci.org/MacPython/netcdf4-python-wheels
* https://s3.amazonaws.com/archive.travis-ci.org/jobs/188055685/log.txt

**Comment by jswhit** [comment]
New release is up on pypi (https://pypi.python.org/pypi/netCDF4/1.2.7).

**Comment by matthew-brett** [comment]
Nice!   Thanks very much for doing that.
