### ISSUE TITLE
Segmentation fault when opening corrupted file

### ISSUE THREAD

**Issue by sfinkens** [Unidata/netcdf4-python#813]
Opening a certain corrupted file (``ftp://ftp-cmsaf.dwd.de/sfinkens/netCDF4_segfault/CTXin20180626013041005SVMSG01MD.nc``)  causes a segmentation fault.

    >>> import netCDF4
    >>> netCDF4.Dataset('CTXin20180626013041005SVMSG01MD.nc', mode='r')
    Segmentation fault

 ``ncdump`` has the same problem, other utilities like ``ncks`` report a proper error message:

    $ ncks -H CTXin20180626013041005SVMSG01MD.nc 
    ERROR: nco__open() unable to open file "CTXin20180626013041005SVMSG01MD.nc"
    nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__open()
    nco_err_exit(): ERROR Error code is -101. Translation into English with nc_strerror(-101) is "NetCDF: HDF error"
    nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)

Maybe the entry "h5dump produced SEGFAULT when dumping corrypted file." in the [hdf5-1.10.2 release notes](https://portal.hdfgroup.org/display/support/HDF5%201.10.2#releasenotes) is related? However it doesn't crash with this file...

This is the output of the netCDF4 test suite:

    not running tst_unicode3.py ...

    netcdf4-python version: 1.3.1
    HDF5 lib version:       1.10.1
    netcdf lib version:     4.5.0
    numpy version           1.14.2
    cython version          0.28.2
    .E....E................................................foo_bar
    ............................................
    ======================================================================
    ERROR: runTest (tst_cdf5.test_cdf5)
    testing NETCDF3_64BIT_DATA format (CDF-5)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/cmsaf/cmsaf-ops3/runsystem/sw/python/2018.01_CentOS/2.7.14/netCDF4-1.3.1/test/tst_cdf5.py", line 19, in setUp
        v = nc.createVariable('var',np.uint8,'dim')
    File "netCDF4/_netCDF4.pyx", line 2437, in netCDF4._netCDF4.Dataset.createVariable
    File "netCDF4/_netCDF4.pyx", line 3389, in netCDF4._netCDF4.Variable.__init__
    File "netCDF4/_netCDF4.pyx", line 1638, in netCDF4._netCDF4._ensure_nc_success
    RuntimeError: NetCDF: Not a valid data type or _FillValue type mismatch

    ======================================================================
    ERROR: runTest (tst_dap.DapTestCase)
    testing access of data over http using opendap
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/cmsaf/cmsaf-ops3/runsystem/sw/python/2018.01_CentOS/2.7.14/netCDF4-1.3.1/test/tst_dap.py", line 23, in runTest
        ncfile = netCDF4.Dataset(URL)
    File "netCDF4/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
    File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
    IOError: [Errno -51] NetCDF: Unknown file format: 'http://remotetest.unidata.ucar.edu/thredds/dodsC/testdods/testData.nc'

    ----------------------------------------------------------------------
    Ran 99 tests in 34.321s

    FAILED (errors=2)

**Comment by sfinkens** [comment]
Upgrading to 1.4.0 solves the problem once, but repeated attempts still cause a segmentation fault

    >>> import netCDF4
    >>> netCDF4.Dataset('CTXin20180626013041005SVMSG01MD.nc', mode='r')
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "netCDF4/_netCDF4.pyx", line 2111, in netCDF4._netCDF4.Dataset.__init__
    File "netCDF4/_netCDF4.pyx", line 1731, in netCDF4._netCDF4._ensure_nc_success
    IOError: [Errno -101] NetCDF: HDF error: 'CTXin20180626013041005SVMSG01MD.nc'
    >>> netCDF4.Dataset('CTXin20180626013041005SVMSG01MD.nc', mode='r')
    *** Error in `python': free(): invalid pointer: 0x00000000013da520 ***
    ======= Backtrace: =========
    /lib64/libc.so.6(+0x7c619)[0x7f3dfbb56619]
    /cmsaf/nfshome/routcm/Modules_CentOS/netcdf/2018.01/lib/libhdf5.so.101(H5MM_xfree+0xe)[0x7f3df42a010e]
    /cmsaf/nfshome/routcm/Modules_CentOS/netcdf/2018.01/lib/libhdf5.so.101(+0x1bf760)[0x7f3df42d2760]
    /cmsaf/nfshome/routcm/Modules_CentOS/netcdf/2018.01/lib/libhdf5.so.101(H5O_msg_reset+0x60)[0x7f3df42d4ae0]
    /cmsaf/nfshome/routcm/Modules_CentOS/netcdf/2018.01/lib/libhdf5.so.101(H5G__link_release_table+0x60)[0x7f3df424d780]
    /cmsaf/nfshome/routcm/Modules_CentOS/netcdf/2018.01/lib/libhdf5.so.101(H5G__dense_iterate+0xc5)[0x7f3df4244755]
    /cmsaf/nfshome/routcm/Modules_CentOS/netcdf/2018.01/lib/libhdf5.so.101(H5G__obj_iterate+0x119)[0x7f3df42553c9]
    /cmsaf/nfshome/routcm/Modules_CentOS/netcdf/2018.01/lib/libhdf5.so.101(H5G_iterate+0x12e)[0x7f3df424c25e]
    /cmsaf/nfshome/routcm/Modules_CentOS/netcdf/2018.01/lib/libhdf5.so.101(H5Literate+0x10f)[0x7f3df428ce1f]
    /cmsaf/nfshome/routcm/Modules_CentOS/netcdf/2018.01/lib/libnetcdf.so.13(+0x6f96b)[0x7f3df495396b]
    /cmsaf/nfshome/routcm/Modules_CentOS/netcdf/2018.01/lib/libnetcdf.so.13(+0x6fd6f)[0x7f3df4953d6f]
    /cmsaf/nfshome/routcm/Modules_CentOS/netcdf/2018.01/lib/libnetcdf.so.13(NC4_open+0xff)[0x7f3df4953f24]
    /cmsaf/nfshome/routcm/Modules_CentOS/netcdf/2018.01/lib/libnetcdf.so.13(NC_open+0x370)[0x7f3df4901d08]
    /cmsaf/nfshome/routcm/Modules_CentOS/netcdf/2018.01/lib/libnetcdf.so.13(nc_open+0x40)[0x7f3df4901040]
    /cmsaf/cmsaf-ops3/sfinkens/virtualenvs/netcdf4_test/lib/python2.7/site-packages/netCDF4/_netCDF4.so(+0x112225)[0x7f3df4ce8225]
    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/libpython2.7.so.1.0(+0xbe82f)[0x7f3dfc88082f]
    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f3dfc815f73]
    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x3aa6)[0x7f3dfc8cb8d6]
    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x80d)[0x7f3dfc8d15ed]
    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x32)[0x7f3dfc8d1722]
    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/libpython2.7.so.1.0(PyRun_InteractiveOneFlags+0x157)[0x7f3dfc8fb567]
    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/libpython2.7.so.1.0(PyRun_InteractiveLoopFlags+0x4e)[0x7f3dfc8fb76e]
    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/libpython2.7.so.1.0(PyRun_AnyFileExFlags+0x3e)[0x7f3dfc8fbf5e]
    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/libpython2.7.so.1.0(Py_Main+0xc4d)[0x7f3dfc91179d]
    /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f3dfbafbc05]
    python[0x40071e]
    ======= Memory map: ========
    00400000-00401000 r-xp 00000000 00:31 921696                             /cmsaf/cmsaf-ops3/sfinkens/virtualenvs/netcdf4_test/bin/python2
    00600000-00601000 r--p 00000000 00:31 921696                             /cmsaf/cmsaf-ops3/sfinkens/virtualenvs/netcdf4_test/bin/python2
    00601000-00602000 rw-p 00001000 00:31 921696                             /cmsaf/cmsaf-ops3/sfinkens/virtualenvs/netcdf4_test/bin/python2
    0132e000-0198f000 rw-p 00000000 00:00 0                                  [heap]
    7f3de4000000-7f3de4021000 rw-p 00000000 00:00 0 
    7f3de4021000-7f3de8000000 ---p 00000000 00:00 0 
    7f3deaef6000-7f3deaf0b000 r-xp 00000000 ca:02 270518                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    7f3deaf0b000-7f3deb10a000 ---p 00015000 ca:02 270518                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    7f3deb10a000-7f3deb10b000 r--p 00014000 ca:02 270518                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    7f3deb10b000-7f3deb10c000 rw-p 00015000 ca:02 270518                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    7f3deb10c000-7f3deb1b4000 r-xp 00000000 00:31 2435774                    /cmsaf/cmsaf-ops3/sfinkens/virtualenvs/netcdf4_test/lib/python2.7/site-packages/cftime/_cftime.so
    7f3deb1b4000-7f3deb3b3000 ---p 000a8000 00:31 2435774                    /cmsaf/cmsaf-ops3/sfinkens/virtualenvs/netcdf4_test/lib/python2.7/site-packages/cftime/_cftime.so
    7f3deb3b3000-7f3deb3b4000 r--p 000a7000 00:31 2435774                    /cmsaf/cmsaf-ops3/sfinkens/virtualenvs/netcdf4_test/lib/python2.7/site-packages/cftime/_cftime.so
    7f3deb3b4000-7f3deb3bc000 rw-p 000a8000 00:31 2435774                    /cmsaf/cmsaf-ops3/sfinkens/virtualenvs/netcdf4_test/lib/python2.7/site-packages/cftime/_cftime.so
    7f3deb3bc000-7f3deb43e000 rw-p 00000000 00:00 0 
    7f3deb43e000-7f3deb444000 r-xp 00000000 00:2c 1092254                    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/python2.7/lib-dynload/strop.so
    7f3deb444000-7f3deb643000 ---p 00006000 00:2c 1092254                    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/python2.7/lib-dynload/strop.so
    7f3deb643000-7f3deb644000 r--p 00005000 00:2c 1092254                    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/python2.7/lib-dynload/strop.so
    7f3deb644000-7f3deb646000 rw-p 00006000 00:2c 1092254                    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/python2.7/lib-dynload/strop.so
    7f3deb646000-7f3deb686000 rw-p 00000000 00:00 0 
    7f3deb6c0000-7f3deb700000 rw-p 00000000 00:00 0 
    7f3deb700000-7f3deb7bb000 r-xp 00000000 00:2c 1065061                    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/python2.7/site-packages/numpy/random/mtrand.so
    7f3deb7bb000-7f3deb9bb000 ---p 000bb000 00:2c 1065061                    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/python2.7/site-packages/numpy/random/mtrand.so
    7f3deb9bb000-7f3deb9e0000 rw-p 000bb000 00:2c 1065061                    /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/python2.7/site-packages/numpy/random/mtrand.so
    7f3deb9e0000-7f3deb9e2000 rw-p 00000000 00:00 0 
    7f3deb9e2000-7f3deb9eb000 r-xp 00000000 00:2c 462011                     /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/python2.7/site-packages/numpy/fft/fftpack_lite.so
    7f3deb9eb000-7f3debbea000 ---p 00009000 00:2c 462011                     /cmsaf/nfshome/routcm/Modules_CentOS/python/2.7.14/lib/python2.7/site-packages/numpy/fft/fftpack_lite.soAborted
