### ISSUE TITLE
exception when a masked array is supplied that uses only a single boolean 

### ISSUE THREAD

**Issue by ReimarBauer** [Unidata/netcdf4-python#847]
The problem seemingly occurs, when a masked array is supplied that uses only a single boolean (np.ma.nomask) instead of a full boolean array.

This worked in 1.4.0

```
import numpy as np
import netCDF4 as nc

a = np.asarray([0, 6, 12])
print(nc.num2date(a, "hours since 2012-10-17T12:00:00.000Z"))  # <- fine
b = np.ma.masked_invalid(a)
print(type(b), b.shape, b.mask)
print(nc.num2date(b, "hours since 2012-10-17T12:00:00.000Z"))  # <- fine
b = np.ma.asarray(a)
print(type(b), b.shape, b.mask)
print(nc.num2date(b, "hours since 2012-10-17T12:00:00.000Z"))  # <- Exception
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cftime/_cftime.pyx", line 290, in cftime._cftime.num2date
  File "cftime/_cftime.pyx", line 1211, in cftime._cftime.utime.num2date
  File "/home/user/miniconda3/envs/simmple/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 279, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/user/miniconda3/envs/simmple/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (3,)
```

**Comment by jswhit** [comment]
cftime is now a separate package - please create an issue at https://github.com/Unidata/cftime

**Comment by dopplershift** [comment]
Can you make sure you're running the latest cftime release? Version 1.0.1 was released with this fix.
