### ISSUE TITLE
Dataset attribute present in py3.6 build but not py2.7 build

### ISSUE THREAD

**Issue by corinnebosley** [Unidata/netcdf4-python#848]
The NetCDF4 method `netCDF4.Dataset.set_always_mask` appears to be present in the Python 3.6 build of netdcdf4, but not in the same build for Python 2.7.

When attempting to set that attribute (to False) in the Python 2.7 build, I get the following error (see end of stacktrace):

```
======================================================================
ERROR: test_monotonic (iris.tests.test_netcdf.TestNetCDFLoad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/net/home/h06/cbosley/Projects/iris/lib/iris/tests/test_netcdf.py", line 56, in test_monotonic
    ('NetCDF', 'testing', 'test_monotonic_coordinate.nc')))
  File "/net/home/h06/cbosley/Projects/iris/lib/iris/__init__.py", line 343, in load
    return _load_collection(uris, constraints, callback).merged().cubes()
  File "/net/home/h06/cbosley/Projects/iris/lib/iris/__init__.py", line 313, in _load_collection
    result = iris.cube._CubeFilterCollection.from_cubes(cubes, constraints)
  File "/net/home/h06/cbosley/Projects/iris/lib/iris/cube.py", line 145, in from_cubes
    for cube in cubes:
  File "/net/home/h06/cbosley/Projects/iris/lib/iris/__init__.py", line 300, in _generate_cubes
    for cube in iris.io.load_files(part_names, callback, constraints):
  File "/net/home/h06/cbosley/Projects/iris/lib/iris/io/__init__.py", line 210, in load_files
    for cube in handling_format_spec.handler(fnames, callback):
  File "/net/home/h06/cbosley/Projects/iris/lib/iris/fileformats/netcdf.py", line 706, in load_cubes
    cf = iris.fileformats.cf.CFReader(filename)
  File "/net/home/h06/cbosley/Projects/iris/lib/iris/fileformats/cf.py", line 942, in __init__
    self._dataset.set_always_mask(False)
  File "netCDF4/_netCDF4.pyx", line 2701, in netCDF4._netCDF4.Dataset.__getattr__
  File "netCDF4/_netCDF4.pyx", line 2647, in netCDF4._netCDF4.Dataset.getncattr
  File "netCDF4/_netCDF4.pyx", line 1277, in netCDF4._netCDF4._get_att
  File "netCDF4/_netCDF4.pyx", line 1733, in netCDF4._netCDF4._ensure_nc_success
AttributeError: NetCDF: Attribute not found
```

This test (and all our tests actually) passes fine with the Python 3.6 build, and I have no problem setting the attribute.

Are you aware of this difference, and if so is there a good reason for it?

**Comment by jswhit** [comment]
You  have an older version of netcdf4-python installed in python 2.7 (check `netCDF4.__version__`)

**Comment by pp-mo** [comment]
Apologies, you are correct !
There is a conda message "The following packages will be DOWNGRADED:" in the build log which we had missed !
