### ISSUE TITLE
Array of compatible shape cannot be broadcasted into Dataset variable

### ISSUE THREAD

**Issue by MiCurry** [Unidata/netcdf4-python#939]
With versions >= 1.5.1 an array of different, but compatible shape to a Dataset variable's shape, cannot be broadcasted into it.

```
import numpy
from netCDF4 import Dataset

mesh = Dataset('mesh.nc', 'w')

nCells = mesh.createDimension('nCells', 100)
TWO = mesh.createDimension('TWO', 2)

mesh.createVariable('cellsOnEdge', 'i', ('nCells', 'TWO',))

cellsOnEdge = numpy.random.randint(1, high=200, size=(nCells.size, TWO.size))

flatten_field = cellsOnEdge.flatten()

print(cellsOnEdge.shape)
print(flatten_field.shape)

# Fails to broadcast flattened array into 2D variable in V > 1.5.1
mesh.variables['cellsOnEdge'][:] = flatten_field
```

With versions < 1.5.1, the flatten array is able to be broadcasted into the variable without an error, but versions >= 1.5.1 gave the following errors:

Version 1.5.1:
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    mesh.variables['cellsOnEdge'][:] = flatten_field
  File "netCDF4/_netCDF4.pyx", line 4796, in netCDF4._netCDF4.Variable.__setitem__
  File "/gpfs/fs1/scratch/mcurry/netcdf4/env/lib/python3.6/site-packages/netCDF4/utils.py", line 352, in _StartCountStride
    datashapenew = datashapenew + (datashape[i],)
IndexError: tuple index out of range
```

Versions >= 1.5.1.1:
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    mesh.variables['cellsOnEdge'][:] = flatten_field
  File "netCDF4/_netCDF4.pyx", line 4796, in netCDF4._netCDF4.Variable.__setitem__
  File "/gpfs/fs1/scratch/mcurry/netcdf4/env/lib/python3.6/site-packages/netCDF4/utils.py", line 365, in _StartCountStride
    datashape = broadcasted_shape(shape, datashape)
  File "/gpfs/fs1/scratch/mcurry/netcdf4/env/lib/python3.6/site-packages/netCDF4/utils.py", line 968, in broadcasted_shape
    return np.broadcast(a, b).shape
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

A work around is very easy, just reshape the variable to have the same shape:
`flatten_field.reshape([nCells, TWO])`

I'm not sure if this was a regression, perhaps it was intentional? Let me know if you have any questions.

**Comment by jswhit** [comment]
The fact that netcdf4-python reshaped a 1d numpy array to fit into a 2d variable was a bug - it didn't work correctly in all cases.  That's why I changed the behavior in 1.5.1 to follow numpy broadcasting rules.

**Comment by MiCurry** [comment]
Ah, I realize that this isn't a function of numpy that I thought it was. Thanks for the info!
